### ISSUE TITLE
user sign up problem

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1031]
getting this in the log: 

```
2016-05-10T15:59:20.907390+00:00 app[web.1]: Started GET "/users/sign_up" for 185.53.227.70 at 2016-05-10 15:59:20 +0000
2016-05-10T15:59:20.915377+00:00 app[web.1]: Processing by RegistrationsController#new as HTML
2016-05-10T15:59:21.102420+00:00 app[web.1]:   Rendered devise/registrations/new.html.erb within layouts/application (1.1ms)
2016-05-10T15:59:21.105749+00:00 app[web.1]:   Rendered layouts/_meta_tags.html.erb (0.9ms)
2016-05-10T15:59:21.106863+00:00 app[web.1]:   Rendered layouts/_head.html.erb (4.2ms)
2016-05-10T15:59:21.116916+00:00 app[web.1]:   Rendered layouts/_flash.html.erb (0.3ms)
2016-05-10T15:59:21.117040+00:00 app[web.1]:   Rendered layouts/_navbar.html.erb (10.0ms)
2016-05-10T15:59:21.122172+00:00 app[web.1]:   Rendered layouts/_sponsors.html.erb (4.8ms)
2016-05-10T15:59:21.144096+00:00 app[web.1]:   Rendered layouts/_footer.html.erb (11.5ms)
2016-05-10T15:59:21.151448+00:00 app[web.1]: Completed 200 OK in 236ms (Views: 32.9ms | ActiveRecord: 25.7ms)
2016-05-10T15:59:21.153611+00:00 app[web.1]: source=rack-timeout id=a70ee76d-880b-4ca1-894c-2a0e4b6ee2e7 wait=0ms timeout=20000ms service=253ms state=completed
2016-05-10T15:59:21.178897+00:00 heroku[router]: at=info method=GET path="/users/sign_up" host=www.agileventures.org request_id=a70ee76d-880b-4ca1-894c-2a0e4b6ee2e7 fwd="185.53.227.70" dyno=web.1 connect=1ms service=275ms status=200 bytes=5860
2016-05-10T15:59:22.212972+00:00 app[web.1]: source=rack-timeout id=8ff19918-5e5f-4ff9-88b2-0119abd9a5a3 wait=0ms timeout=20000ms state=ready
2016-05-10T15:59:22.213882+00:00 app[web.1]: Started GET "/auth/github?origin=%2F" for 185.53.227.70 at 2016-05-10 15:59:22 +0000
2016-05-10T15:59:22.217510+00:00 app[web.1]: I, [2016-05-10T15:59:22.217445 #6]  INFO -- omniauth: (github) Request phase initiated.
2016-05-10T15:59:22.222047+00:00 app[web.1]: source=rack-timeout id=8ff19918-5e5f-4ff9-88b2-0119abd9a5a3 wait=0ms timeout=20000ms service=9ms state=completed
2016-05-10T15:59:22.382254+00:00 app[web.1]: source=rack-timeout id=9996e26e-3b03-4ec4-97ca-f75440bcd2c0 wait=0ms timeout=20000ms state=ready
2016-05-10T15:59:22.382855+00:00 app[web.1]: Started GET "/events/pairing-on-cs169-1-hw1" for 208.115.113.88 at 2016-05-10 15:59:22 +0000
2016-05-10T15:59:22.388028+00:00 app[web.1]: Processing by EventsController#show as */*
2016-05-10T15:59:22.388104+00:00 app[web.1]:   Parameters: {"id"=>"pairing-on-cs169-1-hw1"}
2016-05-10T15:59:22.237329+00:00 heroku[router]: at=info method=GET path="/auth/github?origin=%2F" host=www.agileventures.org request_id=8ff19918-5e5f-4ff9-88b2-0119abd9a5a3 fwd="185.53.227.70" dyno=web.1 connect=1ms service=15ms status=302 bytes=2445
2016-05-10T15:59:22.479418+00:00 app[web.1]:   Rendered events/show.html.erb within layouts/application (4.3ms)
2016-05-10T15:59:22.481542+00:00 app[web.1]:   Rendered layouts/_meta_tags.html.erb (1.2ms)
2016-05-10T15:59:22.483453+00:00 app[web.1]:   Rendered layouts/_head.html.erb (3.4ms)
2016-05-10T15:59:22.489869+00:00 app[web.1]:   Rendered layouts/_flash.html.erb (0.3ms)
2016-05-10T15:59:22.490034+00:00 app[web.1]:   Rendered layouts/_navbar.html.erb (6.4ms)
2016-05-10T15:59:22.493334+00:00 app[web.1]:   Rendered layouts/_sponsors.html.erb (2.9ms)
2016-05-10T15:59:22.499187+00:00 app[web.1]:   Rendered layouts/_footer.html.erb (5.6ms)
2016-05-10T15:59:22.499749+00:00 app[web.1]: Completed 200 OK in 112ms (Views: 15.7ms | ActiveRecord: 18.2ms)
2016-05-10T15:59:22.500819+00:00 app[web.1]: source=rack-timeout id=9996e26e-3b03-4ec4-97ca-f75440bcd2c0 wait=0ms timeout=20000ms service=119ms state=completed
2016-05-10T15:59:22.650151+00:00 app[web.1]: source=rack-timeout id=0c0868bf-a8c9-474b-a47f-1931aedb4e68 wait=0ms timeout=20000ms state=ready
2016-05-10T15:59:22.651156+00:00 app[web.1]: Started GET "/auth/github/callback?code=3158aae838d96bdc8644&origin=%2F&state=72326991e41b7499378c9f1a488b84a3b884bd0691c4b910" for 185.53.227.70 at 2016-05-10 15:59:22 +0000
2016-05-10T15:59:22.654368+00:00 app[web.1]: I, [2016-05-10T15:59:22.654305 #6]  INFO -- omniauth: (github) Callback phase initiated.
2016-05-10T15:59:22.520458+00:00 heroku[router]: at=info method=GET path="/events/pairing-on-cs169-1-hw1" host=www.agileventures.org request_id=9996e26e-3b03-4ec4-97ca-f75440bcd2c0 fwd="208.115.113.88" dyno=web.1 connect=0ms service=123ms status=200 bytes=12968
2016-05-10T15:59:22.752493+00:00 app[web.1]: Processing by AuthenticationsController#create as HTML
2016-05-10T15:59:22.752633+00:00 app[web.1]:   Parameters: {"code"=>"3158aae838d96bdc8644", "origin"=>"/", "state"=>"72326991e41b7499378c9f1a488b84a3b884bd0691c4b910", "provider"=>"github"}
2016-05-10T15:59:22.906421+00:00 app[web.1]: undefined method `async' for #<SlackInviteJob:0x007f363b2962d8>
2016-05-10T15:59:22.906433+00:00 app[web.1]: /app/app/models/user.rb:139:in `send_slack_invite'
2016-05-10T15:59:22.906434+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:432:in `block in make_lambda'
2016-05-10T15:59:22.906456+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:228:in `block in halting_and_conditional'
2016-05-10T15:59:22.906479+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:506:in `block in call'
2016-05-10T15:59:22.906518+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:506:in `each'
2016-05-10T15:59:22.906547+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:506:in `call'
2016-05-10T15:59:22.919446+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_request.text.erb (5.5ms)
2016-05-10T15:59:22.920239+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
2016-05-10T15:59:22.922022+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_session.text.erb (1.4ms)
2016-05-10T15:59:22.922476+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2016-05-10T15:59:22.927511+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_environment.text.erb (4.0ms)
2016-05-10T15:59:22.928933+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.7ms)
2016-05-10T15:59:22.932558+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (0.3ms)
2016-05-10T15:59:22.933746+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
2016-05-10T15:59:22.934697+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_data.text.erb (0.4ms)
2016-05-10T15:59:22.935193+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
2016-05-10T15:59:22.935404+00:00 app[web.1]:   Rendered vendor/bu2016-05-10T15:59:22.935404+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (22.3ms)
2016-05-10T15:59:23.121926+00:00 app[web.1]: 
2016-05-10T15:59:23.121936+00:00 app[web.1]: Sent mail to info@agileventures.org (181.9ms)
2016-05-10T15:59:23.131418+00:00 app[web.1]:   Rendered static_pages/internal_error.html.erb within layouts/application (8.6ms)
2016-05-10T15:59:23.133245+00:00 app[web.1]:   Rendered layouts/_meta_tags.html.erb (1.2ms)
2016-05-10T15:59:23.134469+00:00 app[web.1]:   Rendered layouts/_head.html.erb (2.7ms)
2016-05-10T15:59:23.228339+00:00 app[web.1]:   Rendered layouts/_flash.html.erb (0.5ms)
2016-05-10T15:59:23.228654+00:00 app[web.1]:   Rendered layouts/_navbar.html.erb (94.0ms)
2016-05-10T15:59:23.234268+00:00 app[web.1]:   Rendered layouts/_sponsors.html.erb (4.9ms)
2016-05-10T15:59:23.244655+00:00 app[web.1]:   Rendered layouts/_footer.html.erb (9.9ms)
2016-05-10T15:59:23.246522+00:00 app[web.1]: Completed 500 Internal Server Error in 494ms (Views: 99.4ms | ActiveRecord: 43.7ms)
2016-05-10T15:59:23.252697+00:00 app[web.1]: source=rack-timeout id=0c0868bf-a8c9-474b-a47f-1931aedb4e68 wait=0ms timeout=20000ms service=603ms state=completed
2016-05-10T15:59:23.268544+00:00 heroku[router]: at=info method=GET path="/auth/github/callback?code=3158aae838d96bdc8644&origin=%2F&state=72326991e41b7499378c9f1a488b84a3b884bd0691c4b910" host=www.agileventures.org request_id=0c0868bf-a8c9-474b-a47f-1931aedb4e68 fwd="185.53.227.70" dyno=web.1 connect=1ms service=608ms status=500 bytes=5275
2016-05-10T15:59:26.023531+00:00 heroku[web.1]: Process running mem=702M(136.6%)
2016-05-10T15:59:26.023531+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2016-05-10T15:59:34.798752+00:00 app[web.1]: source=rack-timeout id=0068cd85-f991-46d6-88bc-3ea553a3022a wait=0ms timeout=20000ms state=ready
2016-05-10T15:59:34.816013+00:00 app[web.1]: Started GET "/users/gaspar-ukomski" for 66.249.66.37 at 2016-05-10 15:59:34 +0000
2016-05-10T15:59:34.830934+00:00 app[web.1]: Processing by UsersController#show as HTML
2016-05-10T15:59:34.831035+00:00 app[web.1]:   Parameters: {"id"=>"gaspar-ukomski"}
2016-05-10T15:59:35.429433+00:00 app[web.1]: ActiveRecord::RecordNotFound
2016-05-10T15:59:35.429712+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/friendly_id-5.1.0/lib/friendly_id/finder_methods.rb:23:in `find'
2016-05-10T15:59:35.429747+00:00 app[web.1]: /app/app/controllers/users_controller.rb:76:in `get_user'
2016-05-10T15:59:35.429781+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:432:in `block in make_lambda'
2016-05-10T15:59:35.429816+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:145:in `block in halting_and_conditional'
2016-05-10T15:59:35.429853+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `block in call'
2016-05-10T15:59:35.429883+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `each'
2016-05-10T15:59:35.431288+00:00 app[web.1]:   Rendered static_pages/not_found.html.erb within layouts/application (0.7ms)
2016-05-10T15:59:35.435828+00:00 app[web.1]:   Rendered layouts/_meta_tags.html.erb (1.0ms)
2016-05-10T15:59:35.437195+00:00 app[web.1]:   Rendered layouts/_head.html.erb (2.7ms)
2016-05-10T15:59:35.450127+00:00 app[web.1]:   Rendered layouts/_flash.html.erb (1.2ms)
2016-05-10T15:59:35.450296+00:00 app[web.1]:   Rendered layouts/_navbar.html.erb (12.9ms)
2016-05-10T15:59:35.453723+00:00 app[web.1]:   Rendered layouts/_sponsors.html.erb (2.9ms)
2016-05-10T15:59:35.459955+00:00 app[web.1]:   Rendered layouts/_footer.html.erb (5.8ms)
2016-05-10T15:59:35.460648+00:00 app[web.1]: Completed 404 Not Found in 629ms (Views: 21.3ms | ActiveRecord: 16.7ms)
```

**Comment by mtc2013** [comment]
From the sucker punch gem github:

```Backwards Compatibility

In version ~> 2.0.0, the syntax to enqueue an asynchronous background job has changed from:

LogJob.new.async.perform(...)
to:

LogJob.perform_async(...)```

**Comment by mtc2013** [comment]
We are on 2.02 as of now:

https://github.com/AgileVentures/WebsiteOne/blob/develop/Gemfile.lock#L503

**Comment by tansaku** [comment]
we have a second layer of error with this: `sign_in_and_redirect(:user, authentication.user) is now failing` 

 ```
NoMethodError - undefined method `to_key' for :user:Symbol
Did you mean?  to_query:
```

it looks as if devise has made breaking changes and our tests do not cover this authentication sign up process sufficiently

**Comment by touchps** [comment]
Struggling to test the app using a remote machine. Perhaps a change in `/etc/hosts` file. For now application rebukes with following url.
`http://localhost:3000/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=03ef3f2fa86f2c539b84ee4f1218c9b4ce7c05a4d6cda6ee`

**Comment by tansaku** [comment]
yeah, that was the bug I was getting when I was running on the wrong port - we need to completely review how sign up is tested, because it looks like some critical parts of it aren't ...

**Comment by touchps** [comment]
I'm yet to find a conclusive way of reproducing this issue. The github login worked fine for me. 

Only after deleting my account from db, i got this issue when trying to sign in again using github, but it went away as soon as i cleared authentication table.

**Comment by tansaku** [comment]
it seems that we do not have an acceptance test for the sign up process ...
