### ISSUE TITLE
'webkit_server failed to start' on cloud9

### ISSUE THREAD

**Issue by nab1l** [AgileVentures/WebsiteOne#1057]
Hello,
I'm trying to set up WebSiteOne on cloud 9. 
On project setup  step 6:  i had run specs through rake spec i got much  failed specs  " bundle exec rake spec":

Failures:

  1) dashboard/index.html.erb displays a tab view
     Failure/Error: raise ConnectionError, "#{SERVER_PATH} failed to start."

```
 Capybara::Webkit::ConnectionError:
   /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/bin/webkit_server failed to start.
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:56:in `parse_port'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:42:in `discover_port'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:26:in `start'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/connection.rb:67:in `start_server'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/connection.rb:17:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/driver.rb:16:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/driver.rb:16:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit.rb:15:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit.rb:15:in `block in <top (required)>'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/session.rb:85:in `driver'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/session.rb:71:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:321:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:321:in `current_session'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/dsl.rb:47:in `page'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:53:in `block in after_failed_example'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:352:in `using_session'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:52:in `after_failed_example'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:82:in `block (2 levels) in <top (required)>'
```

  2) dashboard/index.html.erb render and populate map of users includes map
     Failure/Error: raise ConnectionError, "#{SERVER_PATH} failed to start."

```
 Capybara::Webkit::ConnectionError:
   /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/bin/webkit_server failed to start.
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:56:in `parse_port'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:42:in `discover_port'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:26:in `start'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/connection.rb:67:in `start_server'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/connection.rb:17:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/driver.rb:16:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/driver.rb:16:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit.rb:15:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit.rb:15:in `block in <top (required)>'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/session.rb:85:in `driver'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/session.rb:71:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:321:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:321:in `current_session'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/dsl.rb:47:in `page'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:53:in `block in after_failed_example'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:352:in `using_session'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:52:in `after_failed_example'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:82:in `block (2 levels) in <top (required)>'
```

  3) dashboard/index.html.erb render and populate map of users includes map legend
     Failure/Error: raise ConnectionError, "#{SERVER_PATH} failed to start."

```
 Capybara::Webkit::ConnectionError:
   /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/bin/webkit_server failed to start.
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:56:in `parse_port'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:42:in `discover_port'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:26:in `start'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/connection.rb:67:in `start_server'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/connection.rb:17:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/driver.rb:16:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/driver.rb:16:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit.rb:15:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit.rb:15:in `block in <top (required)>'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/session.rb:85:in `driver'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/session.rb:71:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:321:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:321:in `current_session'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/dsl.rb:47:in `page'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:53:in `block in after_failed_example'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:352:in `using_session'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:52:in `after_failed_example'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:82:in `block (2 levels) in <top (required)>'
```

  4) dashboard/index.html.erb render and populate map of users should eq 20
     Failure/Error: raise ConnectionError, "#{SERVER_PATH} failed to start."

```
 Capybara::Webkit::ConnectionError:
   /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/bin/webkit_server failed to start.
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:56:in `parse_port'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:42:in `discover_port'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:26:in `start'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/connection.rb:67:in `start_server'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/connection.rb:17:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/driver.rb:16:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/driver.rb:16:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit.rb:15:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit.rb:15:in `block in <top (required)>'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/session.rb:85:in `driver'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/session.rb:71:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:321:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:321:in `current_session'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/dsl.rb:47:in `page'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:53:in `block in after_failed_example'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:352:in `using_session'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:52:in `after_failed_example'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:82:in `block (2 levels) in <top (required)>'
```

  5) dashboard/index.html.erb displays statistics:  100 Members
     Failure/Error: raise ConnectionError, "#{SERVER_PATH} failed to start."

```
 Capybara::Webkit::ConnectionError:
   /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/bin/webkit_server failed to start.
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:56:in `parse_port'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:42:in `discover_port'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:26:in `start'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/connection.rb:67:in `start_server'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/connection.rb:17:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/driver.rb:16:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/driver.rb:16:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit.rb:15:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit.rb:15:in `block in <top (required)>'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/session.rb:85:in `driver'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/session.rb:71:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:321:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:321:in `current_session'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/dsl.rb:47:in `page'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:53:in `block in after_failed_example'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:352:in `using_session'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:52:in `after_failed_example'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:82:in `block (2 levels) in <top (required)>'
```

  6) dashboard/index.html.erb displays statistics:  40 Documents
     Failure/Error: raise ConnectionError, "#{SERVER_PATH} failed to start."

```
 Capybara::Webkit::ConnectionError:
   /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/bin/webkit_server failed to start.
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:56:in `parse_port'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:42:in `discover_port'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:26:in `start'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/connection.rb:67:in `start_server'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/connection.rb:17:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/driver.rb:16:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/driver.rb:16:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit.rb:15:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit.rb:15:in `block in <top (required)>'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/session.rb:85:in `driver'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/session.rb:71:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:321:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:321:in `current_session'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/dsl.rb:47:in `page'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:53:in `block in after_failed_example'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:352:in `using_session'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:52:in `after_failed_example'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:82:in `block (2 levels) in <top (required)>'
```

  7) dashboard/index.html.erb displays statistics:  10 Articles
     Failure/Error: raise ConnectionError, "#{SERVER_PATH} failed to start."

```
 Capybara::Webkit::ConnectionError:
   /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/bin/webkit_server failed to start.
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:56:in `parse_port'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:42:in `discover_port'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:26:in `start'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/connection.rb:67:in `start_server'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/connection.rb:17:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/driver.rb:16:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/driver.rb:16:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit.rb:15:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit.rb:15:in `block in <top (required)>'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/session.rb:85:in `driver'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/session.rb:71:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:321:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:321:in `current_session'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/dsl.rb:47:in `page'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:53:in `block in after_failed_example'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:352:in `using_session'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:52:in `after_failed_example'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:82:in `block (2 levels) in <top (required)>'
```

  8) dashboard/index.html.erb displays statistics:  5 Projects
     Failure/Error: raise ConnectionError, "#{SERVER_PATH} failed to start."

```
 Capybara::Webkit::ConnectionError:
   /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/bin/webkit_server failed to start.
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:56:in `parse_port'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:42:in `discover_port'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:26:in `start'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/connection.rb:67:in `start_server'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/connection.rb:17:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/driver.rb:16:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/driver.rb:16:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit.rb:15:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit.rb:15:in `block in <top (required)>'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/session.rb:85:in `driver'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/session.rb:71:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:321:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:321:in `current_session'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/dsl.rb:47:in `page'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:53:in `block in after_failed_example'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:352:in `using_session'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:52:in `after_failed_example'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:82:in `block (2 levels) in <top (required)>'
```

  9) dashboard/index.html.erb displays statistics:  200 Scrum Minutes
     Failure/Error: raise ConnectionError, "#{SERVER_PATH} failed to start."

```
 Capybara::Webkit::ConnectionError:
   /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/bin/webkit_server failed to start.
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:56:in `parse_port'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:42:in `discover_port'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/server.rb:26:in `start'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/connection.rb:67:in `start_server'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/connection.rb:17:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/driver.rb:16:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit/driver.rb:16:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit.rb:15:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.11.1/lib/capybara/webkit.rb:15:in `block in <top (required)>'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/session.rb:85:in `driver'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/session.rb:71:in `initialize'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:321:in `new'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:321:in `current_session'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/dsl.rb:47:in `page'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:53:in `block in after_failed_example'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara.rb:352:in `using_session'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:52:in `after_failed_example'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.12/lib/capybara-screenshot/rspec.rb:82:in `block (2 levels) in <top (required)>'
```

Finished in 1 minute 55.88 seconds (files took 59.96 seconds to load)
829 examples, 9 failures

Failed examples:

rspec ./spec/views/dashboard/index.html.erb_spec.rb:14 # dashboard/index.html.erb displays a tab view
rspec ./spec/views/dashboard/index.html.erb_spec.rb:75 # dashboard/index.html.erb render and populate map of users includes map
rspec ./spec/views/dashboard/index.html.erb_spec.rb:71 # dashboard/index.html.erb render and populate map of users includes map legend
rspec ./spec/views/dashboard/index.html.erb_spec.rb:69 # dashboard/index.html.erb render and populate map of users should eq 20
rspec ./spec/views/dashboard/index.html.erb_spec.rb:37 # dashboard/index.html.erb displays statistics:  100 Members
rspec ./spec/views/dashboard/index.html.erb_spec.rb:44 # dashboard/index.html.erb displays statistics:  40 Documents
rspec ./spec/views/dashboard/index.html.erb_spec.rb:23 # dashboard/index.html.erb displays statistics:  10 Articles
rspec ./spec/views/dashboard/index.html.erb_spec.rb:30 # dashboard/index.html.erb displays statistics:  5 Projects
rspec ./spec/views/dashboard/index.html.erb_spec.rb:51 # dashboard/index.html.erb displays statistics:  200 Scrum Minutes

Randomized with seed 30457

Coverage report generated for RSpec to /home/ubuntu/workspace/WebsiteOne/coverage. 1468 / 1578 LOC (93.03%) covered.
[Coveralls] Outside the CI environment, not sending data.

**Comment by tansaku** [comment]
Qt and WebKit not installed perhaps https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit

**Comment by nab1l** [comment]
I installed Qt and compiling capybara webkit, without those the "install bundle" will not completed.

**Comment by tansaku** [comment]
I think we have some more things in https://github.com/AgileVentures/LocalSupport/wiki/C9-install-notes that might help ...

**Comment by tansaku** [comment]
So I note that these specs involved javascript - I just got them to pass by commenting out the screenshot component on line 20 of the spec_helper file:

```ruby
# require 'capybara-screenshot/rspec'
```

I wonder if the screenshot gem just doesn't work on c9 - that's something we don't use on LocalSupport

**Comment by tansaku** [comment]
okay, everything passing with that removed ...
