### ISSUE TITLE
failure when trying to save autograder client meeting notes

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1068]
# The whole system was showing a 500 error until I restarted.

Looking at the logs I saw the following a couple of times:

```
2016-05-27T14:47:13.453511+00:00 app[web.1]: Started OPTIONS "/hangouts/31135932" for 86.145.233.84 at 2016-05-27 14:47:13 +0000
2016-05-27T14:47:13.474651+00:00 app[web.1]:   Parameters: {"id"=>"31135932"}
2016-05-27T14:47:13.521674+00:00 app[web.1]: wrong number of arguments (given 2, expected 0)
2016-05-27T14:47:13.474634+00:00 app[web.1]: Processing by EventInstancesController#update as */*
2016-05-27T14:47:13.522058+00:00 app[web.1]: /app/app/models/event.rb:173:in `schedule'
```

that looks like a call from a hangout

nothing on airbrake about that yet ...

![](https://www.dropbox.com/s/hrn0ll0eob5bbq0/Screenshot%202016-05-27%2015.53.57.png?dl=1)

**Comment by tansaku** [comment]
longer version of the stack trace:

```
2016-05-27T14:47:13.453511+00:00 app[web.1]: Started OPTIONS "/hangouts/31135932" for 86.145.233.84 at 2016-05-27 14:47:13 +0000
2016-05-27T14:47:13.474651+00:00 app[web.1]:   Parameters: {"id"=>"31135932"}
2016-05-27T14:47:13.521674+00:00 app[web.1]: wrong number of arguments (given 2, expected 0)
2016-05-27T14:47:13.474634+00:00 app[web.1]: Processing by EventInstancesController#update as */*
2016-05-27T14:47:13.522058+00:00 app[web.1]: /app/app/models/event.rb:173:in `schedule'
2016-05-27T14:47:13.533501+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
2016-05-27T14:47:13.521936+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/ice_cube-0.11.1/lib/ice_cube/rules/weekly_rule.rb:8:in `initialize'
2016-05-27T14:47:13.532167+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
2016-05-27T14:47:13.531387+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_request.text.erb (0.9ms)
2016-05-27T14:47:13.533021+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_session.text.erb (0.3ms)
2016-05-27T14:47:13.545268+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_data.text.erb (0.4ms)
2016-05-27T14:47:13.522090+00:00 app[web.1]: /app/app/models/event.rb:141:in `occurrences_between'
2016-05-27T14:47:13.543853+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (0.2ms)
2016-05-27T14:47:13.542731+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
2016-05-27T14:47:13.545882+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (16.1ms)
2016-05-27T14:47:13.545718+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2016-05-27T14:47:13.544318+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2016-05-27T14:47:13.521988+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/ice_cube-0.11.1/lib/ice_cube/rule.rb:101:in `new'
2016-05-27T14:47:13.521954+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/ice_cube-0.11.1/lib/ice_cube/rules/weekly_rule.rb:8:in `initialize'
2016-05-27T14:47:13.522026+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/ice_cube-0.11.1/lib/ice_cube/rule.rb:101:in `weekly'
2016-05-27T14:47:13.615556+00:00 app[web.1]: 
2016-05-27T14:47:13.542068+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_environment.text.erb (8.0ms)
2016-05-27T14:47:13.615568+00:00 app[web.1]: Sent mail to info@agileventures.org (67.5ms)
2016-05-27T14:47:13.655409+00:00 app[web.1]: source=rack-timeout id=15467053-b0e3-4d8a-b537-aba71fad3ffe wait=7ms timeout=20000ms service=231ms state=completed
2016-05-27T14:47:13.616813+00:00 app[web.1]:   Rendered static_pages/internal_error.html.erb within layouts/application (0.4ms)
2016-05-27T14:47:13.631250+00:00 app[web.1]:   Rendered layouts/_flash.html.erb (0.4ms)
2016-05-27T14:47:13.618408+00:00 app[web.1]:   Rendered layouts/_meta_tags.html.erb (1.0ms)
2016-05-27T14:47:13.653719+00:00 app[web.1]:   Rendered layouts/_footer.html.erb (10.6ms)
2016-05-27T14:47:13.619847+00:00 app[web.1]:   Rendered layouts/_head.html.erb (2.6ms)
2016-05-27T14:47:13.642621+00:00 app[web.1]:   Rendered layouts/_sponsors.html.erb (10.9ms)
2016-05-27T14:47:13.631497+00:00 app[web.1]:   Rendered layouts/_navbar.html.erb (11.5ms)
2016-05-27T14:47:13.654061+00:00 app[web.1]: Completed 500 Internal Server Error in 179ms (Views: 18.5ms | ActiveRecord: 24.8ms)
2016-05-27T14:47:13.665933+00:00 heroku[router]: at=info method=OPTIONS path="/hangouts/31135932" host=websiteone-production.herokuapp.com request_id=15467053-b0e3-4d8a-b537-aba71fad3ffe fwd="86.145.233.84" dyno=web.1 connect=2ms service=244ms status=500 bytes=4149
2016-05-27T14:47:18.795723+00:00 app[web.1]: wrong number of arguments (given 2, expected 0)
2016-05-27T14:47:18.796139+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/ice_cube-0.11.1/lib/ice_cube/rule.rb:101:in `weekly'
2016-05-27T14:47:18.796181+00:00 app[web.1]: /app/app/models/event.rb:173:in `schedule'
2016-05-27T14:47:18.811132+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
2016-05-27T14:47:18.796184+00:00 app[web.1]: /app/app/models/event.rb:141:in `occurrences_between'
2016-05-27T14:47:18.796079+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/ice_cube-0.11.1/lib/ice_cube/rules/weekly_rule.rb:8:in `initialize'
2016-05-27T14:47:18.657442+00:00 app[web.1]: source=rack-timeout id=a6d32eb9-61b8-43e9-8fa6-fd446e1256bc wait=9ms timeout=20000ms state=ready
2016-05-27T14:47:18.796109+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/ice_cube-0.11.1/lib/ice_cube/rule.rb:101:in `new'
2016-05-27T14:47:18.668786+00:00 app[web.1]: Started GET "/users/sign_up" for 1.164.253.42 at 2016-05-27 14:47:18 +0000
2016-05-27T14:47:18.684189+00:00 app[web.1]: Processing by RegistrationsController#new as HTML
2016-05-27T14:47:18.795973+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/ice_cube-0.11.1/lib/ice_cube/rules/weekly_rule.rb:8:in `initialize'
2016-05-27T14:47:18.809104+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_request.text.erb (1.8ms)
2016-05-27T14:47:18.823116+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
2016-05-27T14:47:18.822510+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_environment.text.erb (9.2ms)
2016-05-27T14:47:18.812325+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_session.text.erb (0.7ms)
2016-05-27T14:47:18.812784+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2016-05-27T14:47:18.824613+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (0.4ms)
2016-05-27T14:47:18.825057+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2016-05-27T14:47:18.826485+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
2016-05-27T14:47:18.826686+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (20.7ms)
2016-05-27T14:47:18.826022+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_data.text.erb (0.4ms)
2016-05-27T14:47:18.994898+00:00 app[web.1]:   Rendered static_pages/internal_error.html.erb within layouts/application (0.4ms)
2016-05-27T14:47:18.953202+00:00 app[web.1]: Sent mail to info@agileventures.org (120.2ms)
2016-05-27T14:47:19.075041+00:00 app[web.1]:   Rendered layouts/_sponsors.html.erb (3.8ms)
2016-05-27T14:47:19.001597+00:00 app[web.1]:   Rendered layouts/_head.html.erb (6.4ms)
2016-05-27T14:47:19.103180+00:00 app[web.1]:   Rendered layouts/_footer.html.erb (27.8ms)
2016-05-27T14:47:19.000427+00:00 app[web.1]:   Rendered layouts/_meta_tags.html.erb (4.9ms)
2016-05-27T14:47:19.070562+00:00 app[web.1]:   Rendered layouts/_flash.html.erb (0.4ms)
2016-05-27T14:47:18.953192+00:00 app[web.1]: 
2016-05-27T14:47:19.105115+00:00 app[web.1]: source=rack-timeout id=a6d32eb9-61b8-43e9-8fa6-fd446e1256bc wait=9ms timeout=20000ms service=448ms state=completed
2016-05-27T14:47:19.070734+00:00 app[web.1]:   Rendered layouts/_navbar.html.erb (68.9ms)
2016-05-27T14:47:19.103602+00:00 app[web.1]: Completed 500 Internal Server Error in 419ms (Views: 97.6ms | ActiveRecord: 58.6ms)
2016-05-27T14:47:19.188506+00:00 heroku[router]: at=info method=GET path="/users/sign_up" host=www.agileventures.org request_id=a6d32eb9-61b8-43e9-8fa6-fd446e1256bc fwd="1.164.253.42" dyno=web.1 connect=0ms service=538ms status=500 bytes=4156
2016-05-27T14:47:29.495358+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/ice_cube-0.11.1/lib/ice_cube/rules/weekly_rule.rb:8:in `initialize'
2016-05-27T14:47:29.495378+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/ice_cube-0.11.1/lib/ice_cube/rules/weekly_rule.rb:8:in `initialize'
2016-05-27T14:47:29.333884+00:00 app[web.1]: Processing by VisitorsController#index as HTML
2016-05-27T14:47:29.270242+00:00 app[web.1]: source=rack-timeout id=87b8ad98-6372-44c3-b494-0ed50c076872 wait=7ms timeout=20000ms state=ready
2016-05-27T14:47:29.272377+00:00 app[web.1]: Started GET "/" for 86.145.233.84 at 2016-05-27 14:47:29 +0000
2016-05-27T14:47:29.495418+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/ice_cube-0.11.1/lib/ice_cube/rule.rb:101:in `new'
2016-05-27T14:47:29.495451+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/ice_cube-0.11.1/lib/ice_cube/rule.rb:101:in `weekly'
2016-05-27T14:47:29.495469+00:00 app[web.1]: /app/app/models/event.rb:173:in `schedule'
2016-05-27T14:47:29.495058+00:00 app[web.1]: wrong number of arguments (given 2, expected 0)
2016-05-27T14:47:29.495504+00:00 app[web.1]: /app/app/models/event.rb:141:in `occurrences_between'
2016-05-27T14:47:29.529069+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_request.text.erb (1.1ms)
2016-05-27T14:47:29.531203+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_session.text.erb (0.8ms)
2016-05-27T14:47:29.529919+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
2016-05-27T14:47:29.548248+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.4ms)
2016-05-27T14:47:29.547462+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_environment.text.erb (3.7ms)
2016-05-27T14:47:29.531692+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
2016-05-27T14:47:29.556012+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (0.3ms)
2016-05-27T14:47:29.556026+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
2016-05-27T14:47:29.566518+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (46.9ms)
2016-05-27T14:47:29.710239+00:00 app[web.1]: 
2016-05-27T14:47:29.565580+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_data.text.erb (14.8ms)
2016-05-27T14:47:29.711481+00:00 app[web.1]:   Rendered static_pages/internal_error.html.erb within layouts/application (0.4ms)
2016-05-27T14:47:29.566262+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.4ms)
2016-05-27T14:47:29.738653+00:00 app[web.1]:   Rendered layouts/_flash.html.erb (0.3ms)
2016-05-27T14:47:29.710253+00:00 app[web.1]: Sent mail to info@agileventures.org (121.4ms)
2016-05-27T14:47:29.713481+00:00 app[web.1]:   Rendered layouts/_meta_tags.html.erb (1.1ms)
2016-05-27T14:47:29.714549+00:00 app[web.1]:   Rendered layouts/_head.html.erb (2.6ms)
2016-05-27T14:47:29.738808+00:00 app[web.1]:   Rendered layouts/_navbar.html.erb (24.2ms)
2016-05-27T14:47:29.850986+00:00 app[web.1]:   Rendered layouts/_footer.html.erb (65.5ms)
```

**Comment by tansaku** [comment]
I wonder if this was some kind of js fail in the hangout sending us an ill formed OPTIONS request - that we need to make sure is handled more gracefully on the server side?

**Comment by tansaku** [comment]
I recently got 500 error on projects page - I think it may be just the kind of error we experience under heavy load  ...

**Comment by tansaku** [comment]
not replicated recently so I will close
