### ISSUE TITLE
Install of PhantomJS fails on CI quite often lately

### ISSUE THREAD

**Issue by diraulo** [AgileVentures/WebsiteOne#1103]
Lately, we've experienced lots of build failure as a result of PhantomJS failing to install.

Semaphore already supports PhantomJS. We just need to specify which version to use.
https://semaphoreci.com/docs/phantomjs.html

I understand that in order to simplify install process for new devs on the project, we added the `phantomjs` gem which then downloads and install PhantomJS on the system. How about removing that and updating docs with instructions to install PhantomJS manually? It's not convenient to have to restart the build on CI every time because of that.

**Comment by diraulo** [comment]
```shell
Phantomjs does not appear to be installed in /home/runner/.phantomjs/2.1.1/x86_64-linux/bin/phantomjs, installing!
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0   333    0     0    440      0 --:--:-- --:--:-- --:--:--   440
bunzip2: phantomjs-2.1.1-linux-x86_64.tar.bz2 is not a bzip2 file.
tar: phantomjs-2.1.1-linux-x86_64.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'phantomjs/poltergeist'.
/home/runner/WebsiteOne/config/application.rb:7:in `<top (required)>'
/home/runner/WebsiteOne/Rakefile:4:in `require'
/home/runner/WebsiteOne/Rakefile:4:in `<top (required)>'
TypeError: no implicit conversion of nil into String
/home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/phantomjs-2.1.1.0/lib/phantomjs/platform.rb:72:in `block in install!'
/home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/phantomjs-2.1.1.0/lib/phantomjs/platform.rb:53:in `chdir'
/home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/phantomjs-2.1.1.0/lib/phantomjs/platform.rb:53:in `install!'
/home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/phantomjs-2.1.1.0/lib/phantomjs/platform.rb:86:in `ensure_installed!'
/home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/phantomjs-2.1.1.0/lib/phantomjs.rb:30:in `platform'
/home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/phantomjs-2.1.1.0/lib/phantomjs.rb:25:in `path'
/home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/phantomjs-2.1.1.0/lib/phantomjs/poltergeist.rb:10:in `<top (required)>'
/home/runner/WebsiteOne/config/application.rb:7:in `<top (required)>'
/home/runner/WebsiteOne/Rakefile:4:in `require'
/home/runner/WebsiteOne/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by tansaku** [comment]
this is a real pain - would be good to have a comprehensive solution

**Comment by tansaku** [comment]
let's try removing the gem and see what happens ...

**Comment by tansaku** [comment]
@diraulo rather than immediately pulling out the gem I've investigated if others have encountered the issue, and it seems they have - I've also open a support ticket with Semaphore: 

```
we're having occasional trouble with what seems like a faulty download? https://github.com/AgileVentures/WebsiteOne/issues/1103

it all works fine on a second or third try - I'm guessing that maybe the download of phantomjs-2.1.1-linux-x86_64.tar.bz2 is failing - we're looking at alternatives to the gem that requires this download, but is there anything about sempahore we could change to help?```

**Comment by tansaku** [comment]
they just replied: 

> Thanks for getting in touch!

> As Semaphore platform has PhantomJS 2.1.1 included, I would like to suggest adding the following command to the setup thread 
change-phantomjs-version 2.1.1
because the default PhantomJS version is 1.9.8.
Afterwards, please expire project's dependency cache by visiting the Admin tab in the Project Settings [Expire Dependency Cache].

> Let me know how things go!

**Comment by tansaku** [comment]
I just changed like so:  

![](https://www.dropbox.com/s/44dux48kiwbxavb/Screenshot%202016-07-04%2010.45.02.png?dl=1)

**Comment by tansaku** [comment]
just moved that to first in the setup and ran a test build on develop, which worked - will re-run a few times to see if this addresses the issue

**Comment by tansaku** [comment]
@diraulo so this might be fixed then?
