### ISSUE TITLE
diagnosing memory leak?

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1172]
At the end of the Martin Fowler scrum today the site was down briefly - I saw no error message in the logs apart from memory related ones:

```
2016-06-30T09:01:52.627822+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2016-06-30T09:01:52.627701+00:00 heroku[web.1]: Process running mem=628M(122.8%)
2016-06-30T09:02:13.882254+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2016-06-30T09:02:13.882254+00:00 heroku[web.1]: Process running mem=628M(122.8%)
2016-06-30T09:02:34.734198+00:00 heroku[web.1]: Process running mem=628M(122.8%)
2016-06-30T09:02:34.734377+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2016-06-30T09:02:53.958315+00:00 app[web.1]: source=rack-timeout id=5b5692aa-dee0-4b02-bd96-03d74d33d0e9 wait=3ms timeout=20000ms state=ready
2016-06-30T09:02:53.958918+00:00 app[web.1]: Started GET "/users/alejandro-babio" for 5.255.250.55 at 2016-06-30 09:02:53 +0000
2016-06-30T09:02:53.964761+00:00 app[web.1]: Processing by UsersController#show as */*
2016-06-30T09:02:53.964961+00:00 app[web.1]:   Parameters: {"id"=>"alejandro-babio"}
2016-06-30T09:02:54.072574+00:00 app[web.1]:   Rendered users/profile/_summary.html.erb (10.1ms)
2016-06-30T09:02:54.131901+00:00 app[web.1]:   Rendered users/profile/_detail.html.erb (58.9ms)
2016-06-30T09:02:54.141195+00:00 app[web.1]:   Rendered users/profile/_videos.html.erb (9.0ms)
2016-06-30T09:02:54.147065+00:00 app[web.1]:   Rendered layouts/_hire_me.html.erb (5.5ms)
2016-06-30T09:02:54.154473+00:00 app[web.1]:   Rendered users/profile/_modal.html.erb (7.1ms)
2016-06-30T09:02:54.154719+00:00 app[web.1]:   Rendered users/show.html.erb within layouts/user_profile_layout (92.6ms)
2016-06-30T09:02:54.156528+00:00 app[web.1]:   Rendered layouts/_meta_tags.html.erb (0.7ms)
2016-06-30T09:02:54.157665+00:00 app[web.1]:   Rendered layouts/_head.html.erb (2.1ms)
2016-06-30T09:02:54.169283+00:00 app[web.1]:   Rendered layouts/_flash.html.erb (0.6ms)
2016-06-30T09:02:54.169457+00:00 app[web.1]:   Rendered layouts/_navbar.html.erb (11.6ms)
2016-06-30T09:02:54.179315+00:00 app[web.1]:   Rendered layouts/_footer.html.erb (9.1ms)
2016-06-30T09:02:54.179702+00:00 app[web.1]:   Rendered layouts/application.html.erb (24.4ms)
2016-06-30T09:02:54.180418+00:00 app[web.1]: Completed 200 OK in 215ms (Views: 74.8ms | ActiveRecord: 48.9ms)
2016-06-30T09:02:54.181581+00:00 app[web.1]: source=rack-timeout id=5b5692aa-dee0-4b02-bd96-03d74d33d0e9 wait=3ms timeout=20000ms service=223ms state=completed
2016-06-30T09:02:54.186975+00:00 heroku[router]: at=info method=GET path="/users/alejandro-babio" host=www.agileventures.org request_id=5b5692aa-dee0-4b02-bd96-03d74d33d0e9 fwd="5.255.250.55" dyno=web.1 connect=1ms service=229ms status=200 bytes=6295
2016-06-30T09:02:55.723428+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2016-06-30T09:02:55.723247+00:00 heroku[web.1]: Process running mem=629M(122.9%)
```

It might be a good idea to investigate the possibility of a memory leak as we get more and more usage of the site: 

https://devcenter.heroku.com/articles/ruby-memory-use

**Comment by tansaku** [comment]
just had this from a user:

> Dear sir, madam,

> For your information,

> When creating an event at agileventures.org in the last half hour I encounter the same error in two different browsers. 

> It states: 500 Internal Error
> Something went terribly wrong

> I go on to try to connect with peers through the gitter chat and using Google Hangouts on Air manually.

> Best,

> Wouter Valentin

I note we had nothing from airbrake ...

**Comment by diraulo** [comment]
@tansaku I rolled back to the previous version of the app on heroku

**Comment by tansaku** [comment]
@diraulo do you think it coincides with something we deployed - or is this just heavy load?

**Comment by tansaku** [comment]
I don't see any errors in the logs apart from the usual ```Error R14 (Memory quota exceeded)``` - does airbrake need upgrading?

**Comment by tansaku** [comment]
I was able to create an event successfully on staging: 

![](https://www.dropbox.com/s/kzzdpeqm61dogb7/Screenshot%202016-07-05%2012.03.59.png?dl=1)

**Comment by diraulo** [comment]
@tansaku here's the error I got before i rolled back:

```script
2016-07-05T10:47:10.861464+00:00 heroku[router]: at=info method=GET path="/users/garyhess999" host=www.agileventures.org request_id=7f95ec4c-1825-4949-b7d2-426fabad23c9 fwd="180.76.15.8" dyno=web.1 connect=0ms service=130ms status=200 bytes=5393
2016-07-05T10:47:18.557348+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2016-07-05T10:47:18.557269+00:00 heroku[web.1]: Process running mem=773M(151.1%)
2016-07-05T10:47:21.004183+00:00 app[web.1]: source=rack-timeout id=b917ece3-e581-4196-8150-0c7261f92543 wait=4ms timeout=20000ms state=ready
2016-07-05T10:47:21.005048+00:00 app[web.1]: Started POST "/events" for 105.184.73.75 at 2016-07-05 10:47:21 +0000
2016-07-05T10:47:21.008022+00:00 app[web.1]: Processing by EventsController#create as HTML
2016-07-05T10:47:21.008078+00:00 app[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"wDJOZq2PyeSYn8ps//ObE19JnNL2uyNe6FDoBxYWFay3S/W+KkJyVcQKKCDI/A3Le8Hniw9aCCytv2wWGLIltg==", "event"=>{"name"=>"Test Event", "category"=>"PairProgramming", "project_id"=>"64", "description"=>"Testing", "duration"=>"30", "repeats"=>"never", "repeats_every_n_weeks"=>"1", "repeats_weekly_each_days_of_the_week"=>[""], "repeat_ends_string"=>"on", "time_zone"=>"UTC"}, "start_date"=>"2016-07-05", "next_date"=>"2016-07-05", "start_time"=>"4:00 PM", "start_time_tz"=>"Africa/Johannesburg", "repeat_ends_on"=>"", "commit"=>"Save"}
2016-07-05T10:47:21.082373+00:00 app[web.1]: unknown attribute 'creator_id' for Event.
2016-07-05T10:47:21.082590+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/attribute_assignment.rb:59:in `rescue in _assign_attribute'
2016-07-05T10:47:21.082623+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
2016-07-05T10:47:21.082673+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
2016-07-05T10:47:21.082674+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/strong_parameters.rb:185:in `each_pair'
2016-07-05T10:47:21.082677+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/strong_parameters.rb:185:in `each_pair'
2016-07-05T10:47:21.082734+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
2016-07-05T10:47:21.090821+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_request.text.erb (1.2ms)
2016-07-05T10:47:21.091843+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.4ms)
2016-07-05T10:47:21.093021+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_session.text.erb (0.7ms)
2016-07-05T10:47:21.093400+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2016-07-05T10:47:21.096806+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_environment.text.erb (3.1ms)
2016-07-05T10:47:21.097184+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2016-07-05T10:47:21.098107+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (0.2ms)
2016-07-05T10:47:21.098482+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2016-07-05T10:47:21.099150+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_data.text.erb (0.3ms)
2016-07-05T10:47:21.099487+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2016-07-05T10:47:21.099645+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (10.9ms
```

**Comment by tansaku** [comment]
@diraulo that makes it look like the migration didn't complete

**Comment by tansaku** [comment]
![](https://www.dropbox.com/s/4la3uqtc0w1ww2k/Screenshot%202016-07-05%2012.06.22.png?dl=1)

**Comment by tansaku** [comment]
Works on staging

```sh
→ heroku run rails console -r staging
Running rails console on ⬢ websiteone-staging... up, run.5171
Loading production environment (Rails 4.2.6)
irb(main):001:0> Event.last.creator_id
=> 2331
irb(main):002:0> 
```

**Comment by diraulo** [comment]
That's what i thought too... But then i ran the migration and got no output from my console

Checking semaphore I get this

```script
Running rake db:migrate on ⬢ websiteone-production... starting, run.1397
Running rake db:migrate on ⬢ websiteone-production... connecting, run.1397
Running rake db:migrate on ⬢ websiteone-production... up, run.1397
Migrating to AddCreatorToEvents (20160627134611)
== 20160627134611 AddCreatorToEvents: migrating ===============================
-- add_column(:events, :creator_id, :integer, {:index=>true})
   -> 0.0099s
-- add_foreign_key(:events, :users, {:column=>:creator_id})
   -> 0.0251s
== 20160627134611 AddCreatorToEvents: migrated (0.0370s) ======================
```

which seems to indicate the the migration was complete on production

**Comment by tansaku** [comment]
hmmm ...

**Comment by tansaku** [comment]
from the rails console it looks like it is there on production ...

```sh
→ heroku run rails c -r production
Running rails c on ⬢ websiteone-production... up, run.1764


Loading production environment (Rails 4.2.6)
irb(main):001:0> 
irb(main):002:0* 
irb(main):003:0* Event.last.creator_id
=> nil
```

Heroku database shards out of sync perhaps?

**Comment by tansaku** [comment]
@diraulo is there more to that stack trace from above - I assume it's triggered from EventController#create line 28, but it would nice to be sure ...

we merge in the creator id in the params here:

![](https://www.dropbox.com/s/qt4vqa0xzm3xfik/Screenshot%202016-07-05%2012.12.08.png?dl=1)

**Comment by diraulo** [comment]
@tansaku Nope that's all I got when I tried to create the event

**Comment by tansaku** [comment]
ah, you saw that attempting event creation - interesting

**Comment by woutersb** [comment]
user comment: I created an event and i did a session from 11:30 UTC till 12:15 UTC and it seemed normal. -- Wouter

**Comment by tansaku** [comment]
so note that @woutersb's issue was separate from the memory leak which I think we still have ...

**Comment by tansaku** [comment]
we should profile the site - or break up the monolith? ... websockets from hangouts?

**Comment by tansaku** [comment]
Should look at: https://devcenter.heroku.com/articles/log-runtime-metrics

**Comment by tansaku** [comment]
also read: https://devcenter.heroku.com/articles/dynos

**Comment by tansaku** [comment]
https://blog.codeship.com/debugging-a-memory-leak-on-heroku/

**Comment by sampritipanda** [comment]
I did a little bit of investigation using `log-runtime-metrics` on websiteone-develop and noticed that the site's memory usage steadily increases (by about 0.1 mb every 10 seconds) even if there are no requests made to it.

This is very weird because we don't have any background-jobs running on the app.

**Comment by tansaku** [comment]
We do have scheduled jobs now though that are checking github commit counts and saving users to update karma and stuff

**Comment by tansaku** [comment]
And geocoding people

**Comment by tansaku** [comment]
Hmm, but they should only be running on production ... I wonder if some aspect of our site is starting processes that keep running ...

**Comment by sampritipanda** [comment]
http://stackoverflow.com/questions/12397208/memory-grows-indefinitely-in-an-empty-rails-app#comment17124304_12397208

This suggests updating the new_relic gem to the latest version to fix the memory leak.

**Comment by tansaku** [comment]
@sampritipanda has been doing stress tests on develop and his local instance - using curl in an infinite loop.  Will be very interested to see what we can work out ...

**Comment by tansaku** [comment]
@sampritipanda want to do a PR for a new_relic gem update?  I notice that SO was from 2012, but still worth a try ...

**Comment by tansaku** [comment]
we're trying updating new_relic gem in #1270

**Comment by tansaku** [comment]
we're comparing memory usage - an older pr got at least one critical memory warning:

![critical error](https://www.dropbox.com/s/l977vrmlq3ovmko/Screenshot%202016-09-15%2016.59.47.png?dl=1)

no relic updated gem version has not been running as long, but no critical memory error as yet:

![relic update](https://www.dropbox.com/s/9wa23hubq16903h/Screenshot%202016-09-15%2017.01.08.png?dl=1)

**Comment by tansaku** [comment]
reviewing these two on friday we saw critical memory errors on both, and so started looking at other issues, including how much memory each gem was using, and the number of concurrent workers ... it looks like production only has a single worker - while the nearest_time_zone gem seems to give the largest memory hit with 61 Mb ...

**Comment by tansaku** [comment]
so looks like removing nearest_timezone does appear to reduce resting base memory by 10% or so.  However that's on develop mirroring production, and production has a much higher load than develop, so it's unclear if that alone will resolve the problem.
