### ISSUE TITLE
errors on staging

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1451]
so previously I fixed up some staging errors that were related to projects (i think it was due to some nils in followers or something), but I notice that we're getting something similar in users on staging, e.g. 

```
2016-12-07T18:16:15.269510+00:00 app[web.1]: Processing by UsersController#show as HTML
2016-12-07T18:16:15.269538+00:00 app[web.1]:   Parameters: {"id"=>"bryan-yap"}
2016-12-07T18:16:15.381878+00:00 app[web.1]:   Rendered users/profile/_premium_upgrade.html.erb (1.6ms)
2016-12-07T18:16:15.382233+00:00 app[web.1]:   Rendered users/profile/_summary.html.erb (13.3ms)
2016-12-07T18:16:15.410751+00:00 app[web.1]:   Rendered users/profile/_detail.html.erb (28.3ms)
2016-12-07T18:16:15.410953+00:00 app[web.1]:   Rendered users/show.html.erb within layouts/user_profile_layout (42.4ms)
2016-12-07T18:16:15.411240+00:00 app[web.1]: undefined method `id' for nil:NilClass
2016-12-07T18:16:15.411277+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/acts_as_follower-0.2.1/lib/acts_as_follower/follow_scopes.rb:10:in `for_followable'
2016-12-07T18:16:15.411300+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:70:in `block in for_followable'
2016-12-07T18:16:15.411329+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation.rb:302:in `scoping'
2016-12-07T18:16:15.411356+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:70:in `for_followable'
2016-12-07T18:16:15.411383+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/acts_as_follower-0.2.1/lib/acts_as_follower/follower.rb:20:in `following?'
2016-12-07T18:16:15.411412+00:00 app[web.1]: /app/app/presenters/users/user_presenter.rb:24:in `block in contributions'
```

and 

```
2016-12-07T18:19:54.170720+00:00 app[web.1]: Processing by UsersController#show as HTML
2016-12-07T18:19:54.268218+00:00 app[web.1]:   Rendered users/profile/_premium_upgrade.html.erb (0.9ms)
2016-12-07T18:19:54.170761+00:00 app[web.1]:   Parameters: {"id"=>"pavel-gimelberg"}
2016-12-07T18:19:54.268338+00:00 app[web.1]:   Rendered users/profile/_summary.html.erb (8.0ms)
2016-12-07T18:19:54.299586+00:00 app[web.1]:   Rendered users/profile/_detail.html.erb (31.0ms)
2016-12-07T18:19:54.299698+00:00 app[web.1]:   Rendered users/show.html.erb within layouts/user_profile_layout (39.7ms)
2016-12-07T18:19:54.299861+00:00 app[web.1]: undefined method `hangouts_attended_with_more_than_one_participant' for nil:NilClass
2016-12-07T18:19:54.299882+00:00 app[web.1]: /app/app/views/users/profile/_detail.html.erb:65:in `_app_views_users_profile__detail_html_erb__3103822337940728505_70243903964220'
2016-12-07T18:19:54.299918+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template.rb:145:in `block in render'
2016-12-07T18:19:54.299945+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `block in instrument'
2016-12-07T18:19:54.299975+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2016-12-07T18:19:54.299979+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `instrument'
2016-12-07T18:19:54.300002+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template.rb:333:in `instrument'
```

when trying to look at individual users.

We don't get this on develop.

I think this must be related to data integrity issues, but I wish the app would just not display stuff rather than failing hard - wonder if we can fix that up somehow ...

**Comment by tansaku** [comment]
I think we've fixed this by copying our production data to staging
