### ISSUE TITLE
500 error for events page

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1635]
from the logs

```
2017-04-24T15:27:42.570276+00:00 app[web.1]: Started GET "/events" for 86.145.234.99 at 2017-04-24 15:27:42 +0000
2017-04-24T15:27:42.575338+00:00 app[web.1]: Processing by EventsController#index as HTML
2017-04-24T15:27:52.226624+00:00 heroku[scheduler.6609]: Process running mem=551M(107.8%)
2017-04-24T15:27:52.226624+00:00 heroku[scheduler.6609]: Error R14 (Memory quota exceeded)
2017-04-24T15:27:58.043723+00:00 heroku[web.1]: Process running mem=716M(139.9%)
2017-04-24T15:27:58.043723+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2017-04-24T15:28:02.670179+00:00 app[web.1]: source=rack-timeout id=dde517a3-9c18-44fd-a3b8-2bc0b7fd488c wait=2ms timeout=20000ms service=20101ms state=timed_out
2017-04-24T15:28:02.679318+00:00 app[web.1]: Request waited 2ms, then ran for longer than 20000ms
2017-04-24T15:28:02.680489+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/time/calculations.rb:233:in `minus_with_duration'
2017-04-24T15:28:02.680530+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/time/calculations.rb:244:in `minus_with_coercion'
2017-04-24T15:28:02.680569+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/time_with_zone.rb:265:in `-'
2017-04-24T15:28:02.680607+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/ice_cube-0.11.1/lib/ice_cube/time_util.rb:206:in `dst_change'
2017-04-24T15:28:02.680645+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/ice_cube-0.11.1/lib/ice_cube/validations/lock.rb:43:in `validate_hour_lock'
2017-04-24T15:28:02.680706+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/ice_cube-0.11.1/lib/ice_cube/validations/lock.rb:18:in `validate'
2017-04-24T15:28:02.689941+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_request.text.erb (0.9ms)
2017-04-24T15:28:02.690861+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.4ms)
2017-04-24T15:28:02.692121+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_session.text.erb (0.7ms)
2017-04-24T15:28:02.692583+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2017-04-24T15:28:02.700328+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_environment.text.erb (6.7ms)
2017-04-24T15:28:02.700940+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
2017-04-24T15:28:02.702271+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (0.2ms)
2017-04-24T15:28:02.702719+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2017-04-24T15:28:02.703663+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_data.text.erb (0.4ms)
2017-04-24T15:28:02.704111+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2017-04-24T15:28:02.708978+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (20.7ms)
2017-04-24T15:28:02.775024+00:00 app[web.1]: 
2017-04-24T15:28:02.775027+00:00 app[web.1]: Sent mail to info@agileventures.org (64.0ms)
2017-04-24T15:28:02.776652+00:00 app[web.1]:   Rendered static_pages/internal_error.html.erb within layouts/application (0.5ms)
2017-04-24T15:28:02.778760+00:00 app[web.1]:   Rendered layouts/_meta_tags.html.erb (1.3ms)
2017-04-24T15:28:02.780435+00:00 app[web.1]:   Rendered layouts/_head.html.erb (3.4ms)
2017-04-24T15:28:02.795051+00:00 app[web.1]:   Rendered layouts/_flash.html.erb (0.2ms)
2017-04-24T15:28:02.795208+00:00 app[web.1]:   Rendered layouts/_navbar.html.erb (14.1ms)
2017-04-24T15:28:02.797664+00:00 app[web.1]:   Rendered layouts/_sponsors.html.erb (2.1ms)
2017-04-24T15:28:02.808692+00:00 app[web.1]:   Rendered layouts/_footer.html.erb (4.9ms)
2017-04-24T15:28:02.809066+00:00 app[web.1]: Completed 500 Internal Server Error in 20234ms (Views: 19.8ms | ActiveRecord: 124.5ms)
```

**Comment by mtc2013** [comment]
This issue recurred today.

Worried that it is load dependent as evidenced by intermittency, or network dependent.

**Comment by tansaku** [comment]
so the events page was down for me again, then I reloaded and it showed up ... I've experimented with upgrading us to heroku's $25 a month setup to see if that helps ...

but it hasn't helped and we're getting the same error

 ```/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/time/zones.rb:56:in `find_zone!'```

and now a different one:

``` /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/time_zone_conversion.rb:24:in `convert_time_to_time_zone'````

makes me wonder if there's an event with a corrupt timezone or something ...

we just cloned the production data to staging - wonder if I can replicate there ...

same 500 error on staging

different part of ice_cube this time in log
```/app/vendor/bundle/ruby/2.3.0/gems/ice_cube-0.11.1/lib/ice_cube/time_util.rb:255:in `adjust'```

**Comment by tansaku** [comment]
Develop server is fine ... https://develop.agileventures.org/events .. wonder if I should bring staging data onto develop ...?

I've pulled the production data onto my local machine and the events does take much longer to load ...

Completed 200 OK in 35596ms (Views: 359.4ms | ActiveRecord: 80.0ms)

Here's the full trace:

```Started GET "/events" for ::1 at 2017-05-03 10:31:44 +0000
Processing by EventsController#index as HTML
  Event Load (2.0ms)  SELECT "events".* FROM "events" WHERE "events"."category" = $1  [["category", "Scrum"]]
  Event Load (9.7ms)  SELECT "events".* FROM "events"
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=1064ms state=active
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=2066ms state=active
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=3075ms state=active
  EventInstance Load (5.6ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 1985]]
  EventInstance Load (0.5ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 2]]
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=4078ms state=active
  EventInstance Load (0.5ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 3]]
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=5075ms state=active
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=6081ms state=active
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=7085ms state=active
  EventInstance Load (0.5ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 10]]
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 1985]]
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 2]]
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=8090ms state=active
  EventInstance Load (0.5ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 2640]]
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 3]]
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=9093ms state=active
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=10094ms state=active
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=11096ms state=active
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 1985]]
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 2]]
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=12101ms state=active
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 3]]
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=13105ms state=active
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=14004ms state=active
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=15003ms state=active
  EventInstance Load (5.9ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 2676]]
  EventInstance Load (0.5ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 51]]
  EventInstance Load (0.4ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 2544]]
  EventInstance Load (2.1ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 1106]]
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 1985]]
  EventInstance Load (2.2ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 2528]]
  EventInstance Load (2.1ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 1679]]
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 1985]]
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 1985]]
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 2]]
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=16002ms state=active
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 2640]]
  EventInstance Load (0.5ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 2518]]
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 3]]
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=17004ms state=active
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=18001ms state=active
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=19001ms state=active
  EventInstance Load (2.3ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 2695]]
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 10]]
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 1985]]
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 2]]
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=20003ms state=active
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 3]]
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=21004ms state=active
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=22004ms state=active
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=23004ms state=active
  EventInstance Load (2.5ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 2675]]
  EventInstance Load (1.7ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 84]]
  EventInstance Load (2.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 2688]]
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 1985]]
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 2]]
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=24002ms state=active
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 3]]
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=25005ms state=active
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=26004ms state=active
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=27004ms state=active
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 10]]
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 1985]]
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 2]]
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=28000ms state=active
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 2640]]
  CACHE (0.1ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 3]]
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=29005ms state=active
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=30002ms state=active
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=31003ms state=active
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 1985]]
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 2]]
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=32003ms state=active
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 3]]
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=33004ms state=active
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=34003ms state=active
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=35004ms state=active
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 2676]]
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 51]]
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 2544]]
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 1106]]
  CACHE (0.0ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1  ORDER BY "event_instances"."id" DESC LIMIT 1  [["event_id", 1985]]
  Project Load (9.9ms)  SELECT "projects".* FROM "projects"
  EventInstance Load (3.9ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1 AND (updated_at BETWEEN '2017-05-02 10:34:50.384051' AND '2017-05-03 23:59:59.000000')  ORDER BY "event_instances"."updated_at" DESC LIMIT 1  [["event_id", 1985]]
  EventInstance Load (3.2ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1 AND (updated_at BETWEEN '2017-05-02 10:32:35.390819' AND '2017-05-03 23:59:59.000000')  ORDER BY "event_instances"."updated_at" DESC LIMIT 1  [["event_id", 2]]
  EventInstance Load (5.1ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1 AND (updated_at BETWEEN '2017-05-02 10:32:35.396120' AND '2017-05-03 23:59:59.000000')  ORDER BY "event_instances"."updated_at" DESC LIMIT 1  [["event_id", 3]]
  EventInstance Load (2.9ms)  SELECT  "event_instances".* FROM "event_instances" WHERE "event_instances"."event_id" = $1 AND (updated_at BETWEEN '2017-05-02 10:32:35.410506' AND '2017-05-03 23:59:59.000000')  ORDER BY "event_instances"."updated_at" DESC LIMIT 1  [["event_id", 10]]
  Rendered events/index.html.erb within layouts/application (90.2ms)
  Rendered layouts/_meta_tags.html.erb (5.0ms)
  Rendered layouts/_head.html.erb (95.6ms)
  StaticPage Load (0.5ms)  SELECT  "static_pages".* FROM "static_pages" WHERE "static_pages"."title" = $1 LIMIT 1  [["title", "About Us"]]
  StaticPage Load (0.4ms)  SELECT  "static_pages".* FROM "static_pages" WHERE "static_pages"."title" = $1 LIMIT 1  [["title", "Pricing"]]
  StaticPage Load (0.4ms)  SELECT  "static_pages".* FROM "static_pages" WHERE "static_pages"."slug" = $1 LIMIT 1  [["slug", "Pricing"]]
  StaticPage Load (0.5ms)  SELECT  "static_pages".* FROM "static_pages" WHERE "static_pages"."title" = $1 LIMIT 1  [["title", "Getting started"]]
  Rendered layouts/_flash.html.erb (0.6ms)
  Rendered layouts/_navbar.html.erb (152.9ms)
  StaticPage Load (0.5ms)  SELECT  "static_pages".* FROM "static_pages" WHERE "static_pages"."title" = $1 LIMIT 1  [["title", "Sponsors"]]
  Rendered layouts/_sponsors.html.erb (10.4ms)
  CACHE (0.0ms)  SELECT  "static_pages".* FROM "static_pages" WHERE "static_pages"."title" = $1 LIMIT 1  [["title", "About Us"]]
  StaticPage Load (0.4ms)  SELECT  "static_pages".* FROM "static_pages" WHERE "static_pages"."title" = $1 LIMIT 1  [["title", "Getting Started"]]
  StaticPage Load (0.4ms)  SELECT  "static_pages".* FROM "static_pages" WHERE "static_pages"."slug" = $1 LIMIT 1  [["slug", "Getting Started"]]
  CACHE (0.0ms)  SELECT  "static_pages".* FROM "static_pages" WHERE "static_pages"."title" = $1 LIMIT 1  [["title", "Sponsors"]]
  Rendered layouts/_footer.html.erb (4.4ms)
Completed 200 OK in 35596ms (Views: 359.4ms | ActiveRecord: 80.0ms)
source=rack-timeout id=a8ca0f14641d4267c391c321eff5c0ca timeout=200000000000ms service=35753ms state=completed
source=rack-timeout id=5a254c337d23bcd9bcda193f35c0c1d7 timeout=200000000000ms state=ready
source=rack-timeout id=5a254c337d23bcd9bcda193f35c0c1d7 timeout=200000000000ms service=0ms state=active```

**Comment by tansaku** [comment]
I tried deleting one repeating event to see if that speeded things up but no joy - after that there are only 37 events displayed, but it's still taking over 30 seconds to load ... and it was really snappy before I pulled down the latest production data ... is there something about a particular event ...?

**Comment by tansaku** [comment]
there appears to be a 2 to 3 second wait after every query on the event instances table ...

**Comment by tansaku** [comment]
loading all the event instances kicked off by the `Event.upcoming_events` command takes over 10 seconds on the rails console locally ...

**Comment by tansaku** [comment]
same command returns almost instantly on develop ... and on production it takes nearly 20 seconds ...

**Comment by tansaku** [comment]
I'm currently looking at the elements of that method:

```
  def self.upcoming_events(project=nil)
    events = Event.base_events(project).inject([]) do |memo, event|
      memo << event.next_occurrences
    end.flatten.sort_by { |e| e[:time] }
    Event.remove_past_events(events)
  end
```

generating the events itself takes not much more than a second if I exclude the flattening and sorting .  Flattening and sorting also seem to take next to no time (on local machine with production data).  ```Event.remove_past_events(events)``` seems to be taking all the time ...

**Comment by tansaku** [comment]
so it's ```  def self.remove_past_events(events)
    events.delete_if {|event| !event[:event].event_instances.last.try(:live?) &&
                           (event[:time] + event[:event].duration.minutes) < Time.current}
  end
``` that's slowing us down ...

**Comment by tansaku** [comment]
basically it's that as the number of eventinstances increases it is slower and slower to grab the last one - some of the scrums have over 400 event_instances, and the daily scrums appear multiple times in the list so we are repeatedly looking for the last event instance multiple times over ...
