### ISSUE TITLE
Can we get good reporting for 500 errors?

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1808]
I just got a 500 error going to an event page.  I just had a quick look in the logs and see this:

```
2017-09-05T11:00:41.951305+00:00 app[web.1]: source=rack-timeout id=0d0de188-feb9-465b-b19a-25b81c4a2f54 wait=8ms timeout=20000ms state=ready
2017-09-05T11:00:41.955638+00:00 app[web.1]: Started GET "/events/2" for 86.145.233.255 at 2017-09-05 11:00:41 +0000
2017-09-05T11:00:41.961437+00:00 app[web.1]: Processing by EventsController#show as HTML
2017-09-05T11:00:41.961490+00:00 app[web.1]:   Parameters: {"id"=>"2"}
2017-09-05T11:00:42.454497+00:00 app[web.1]: source=rack-timeout id=f39625fa-89af-4093-8c97-d249748cf412 wait=109ms timeout=20000ms state=ready
2017-09-05T11:00:42.651980+00:00 app[web.1]: Started GET "/events/2" for 86.145.233.255 at 2017-09-05 11:00:42 +0000
2017-09-05T11:00:42.754025+00:00 app[web.1]: Processing by EventsController#show as HTML
2017-09-05T11:00:42.754046+00:00 app[web.1]:   Parameters: {"id"=>"2"}
2017-09-05T11:00:53.179611+00:00 app[web.1]:   Rendered event_instances/_hangout_button.html.erb (2.2ms)
2017-09-05T11:00:55.793712+00:00 app[web.1]:   Rendered event_instances/_hangout_button.html.erb (0.9ms)
2017-09-05T11:01:02.105955+00:00 app[web.1]: source=rack-timeout id=0d0de188-feb9-465b-b19a-25b81c4a2f54 wait=8ms timeout=20000ms service=20155ms state=timed_out
2017-09-05T11:01:02.315478+00:00 app[web.1]:   Rendered events/show.html.erb within layouts/application (20077.3ms)
2017-09-05T11:01:02.315640+00:00 app[web.1]: Request waited 8ms, then ran for longer than 20000ms
2017-09-05T11:01:02.315663+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `exec_prepared'
2017-09-05T11:01:02.315690+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `block in exec_cache'
2017-09-05T11:01:02.315719+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
2017-09-05T11:01:02.315744+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2017-09-05T11:01:02.315766+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
2017-09-05T11:01:02.315788+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:601:in `exec_cache'
2017-09-05T11:01:02.327899+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_request.text.erb (0.7ms)
2017-09-05T11:01:02.328605+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2017-09-05T11:01:02.329931+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_session.text.erb (0.8ms)
2017-09-05T11:01:02.417443+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_environment.text.erb (3.1ms)
2017-09-05T11:01:02.412796+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.4ms)
2017-09-05T11:01:02.417445+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2017-09-05T11:01:02.418093+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (0.2ms)
2017-09-05T11:01:02.419988+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (93.5ms)
2017-09-05T11:01:02.419804+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2017-09-05T11:01:02.418562+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2017-09-05T11:01:02.419386+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_data.text.erb (0.3ms)
2017-09-05T11:01:02.615753+00:00 app[web.1]: source=rack-timeout id=f39625fa-89af-4093-8c97-d249748cf412 wait=109ms timeout=20000ms service=20161ms state=timed_out
2017-09-05T11:01:02.621115+00:00 app[web.1]:   Rendered events/show.html.erb within layouts/application (18956.0ms)
2017-09-05T11:01:02.621366+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/time_with_zone.rb:391:in `year'
2017-09-05T11:01:02.621470+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/core_ext/date_and_time/zones.rb:34:in `new'
2017-09-05T11:01:02.621504+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/core_ext/date_and_time/zones.rb:34:in `time_with_zone'
2017-09-05T11:01:02.621406+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/time_with_zone.rb:391:in `transfer_time_values_to_utc_constructor'
2017-09-05T11:01:02.621328+00:00 app[web.1]: Request waited 109ms, then ran for longer than 20000ms
2017-09-05T11:01:02.621436+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/time_with_zone.rb:48:in `initialize'
2017-09-05T11:01:02.621538+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/core_ext/date_and_time/zones.rb:24:in `in_time_zone'
2017-09-05T11:01:02.662978+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_request.text.erb (1.0ms)
2017-09-05T11:01:02.663802+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
2017-09-05T11:01:02.665891+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
2017-09-05T11:01:02.665387+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_session.text.erb (0.8ms)
2017-09-05T11:01:02.672622+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_environment.text.erb (6.1ms)
2017-09-05T11:01:02.673173+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2017-09-05T11:01:02.678064+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (3.8ms)
2017-09-05T11:01:02.678569+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2017-09-05T11:01:02.679484+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_data.text.erb (0.4ms)
2017-09-05T11:01:02.679995+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2017-09-05T11:01:02.680222+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (27.2ms)
2017-09-05T11:01:02.793771+00:00 app[web.1]: 
2017-09-05T11:01:02.793777+00:00 app[web.1]: Sent mail to info@agileventures.org (361.4ms)
2017-09-05T11:01:02.796244+00:00 app[web.1]:   Rendered static_pages/internal_error.html.erb within layouts/application (1.0ms)
2017-09-05T11:01:02.798425+00:00 app[web.1]:   Rendered layouts/_meta_tags.html.erb (1.0ms)
2017-09-05T11:01:02.799705+00:00 app[web.1]:   Rendered layouts/_head.html.erb (2.7ms)
2017-09-05T11:01:02.840017+00:00 app[web.1]:   Rendered layouts/_flash.html.erb (0.3ms)
2017-09-05T11:01:02.840144+00:00 app[web.1]:   Rendered layouts/_navbar.html.erb (40.2ms)
2017-09-05T11:01:02.850045+00:00 app[web.1]:   Rendered layouts/_sponsors.html.erb (9.5ms)
2017-09-05T11:01:02.911354+00:00 app[web.1]:   Rendered layouts/_footer.html.erb (51.4ms)
2017-09-05T11:01:02.911767+00:00 app[web.1]: Completed 500 Internal Server Error in 20950ms (Views: 32.8ms | ActiveRecord: 422.6ms)
2017-09-05T11:01:02.913632+00:00 app[web.1]: source=rack-timeout id=0d0de188-feb9-465b-b19a-25b81c4a2f54 wait=8ms timeout=20000ms service=20962ms state=completed

```

which seems to correspond to the action that I took ... looks like maybe the database getting stuck? fixed on a refresh ... says info@agileventures.org was emailed? but maybe that's inaccurate or another thread. 

So I need to work out here if airbrake is not supposed to catch 500 rails errors:

https://www.google.co.uk/search?q=why+does+airbrake+not+catch+rails+500+errors

or if we just have it configured incorrectly.

Either way if users are occasionally encountering these 500 errors I would like it tracked and to be offering them more apologies when it does ...

**Comment by tansaku** [comment]
we had this from airbrake:

> Normally, you don't need to wrap Airbrake.configure  with if Rails.env.production?  (or similar) checks. This is not something I recommend because ignore_environments should "just work".

> I can see that you use rack-timeout which raises those exceptions. I set up a test rails app with that gem and added a sleep to my controller. I received the following results in the logs: https://gist.github.com/kyrylo/92a49b65004713a133e192c467230524

> I received the following error on Airbrake:  Rack::Timeout::RequestTimeoutException: Request ran for longer than 1000ms

> I can see that it works as expected. We shouldn't exclude the possibility of an issue with rack-timeout, although I don't have any experience with it. Normally, Airbrake should report error 500, but I cannot reproduce the described issue. If you can show steps that demonstrate how to reproduce it, I would be able to look into that.

**Comment by tansaku** [comment]
https://github.com/AgileVentures/WebsiteOne/blob/develop/config/initializers/airbrake.rb

**Comment by tansaku** [comment]
I also notice that we have code that is supposed to send us an email when we have a 500 error ... I don't get them - we get other emails from the system, but not these 500 ones.  We have a test indicating that errors should go out:

https://github.com/AgileVentures/WebsiteOne/blob/develop/spec/lib/custom_errors_spec.rb#L52

this is the exception notifier:

https://github.com/AgileVentures/WebsiteOne/blob/develop/lib/custom_errors.rb#L22

looks like our ExceptionNotifier is not working ... this gem perhaps?

https://github.com/smartinez87/exception_notification

**Comment by tansaku** [comment]
Robert was suggesting we might have more luck with sentry? https://sentry.io/welcome/

although I do worry that we have custom code that's trying to send us emails that will interfere with anything we try to install.

need a hackathon to get to the bottom of it ...

**Comment by tansaku** [comment]
wonder if this is related? http://guides.rubyonrails.org/configuring.html#configuring-middleware

**Comment by tansaku** [comment]
I guess what I need is a setup where I can generate a 500 error and trace through what happens ... first locally and then maybe on a heroku instance?

**Comment by tansaku** [comment]
interesting there is an airbrake test we can use:

https://github.com/airbrake/airbrake#configuration

```
rake airbrake:test
```

Other thing to do is to comment out all the custom error notification we have set up ...

**Comment by tansaku** [comment]
but that test not working:

```
→ rake airbrake:test
rake aborted!
Don't know how to build task 'airbrake:test' (see --tasks)
```

**Comment by tansaku** [comment]
okay, so it works in production mode - I think the issue we have is that our custom error handling is blocking airbrake, and the ExceptionNotifier gem is not doing it's job for us - so I've turned off custom errors for the moment ... perhaps what we need is to manually call airbrake instead of ExceptionNotifier?
