### ISSUE TITLE
500 error on event show page and general slowness for Martin Fowler and Kent Beck scrums

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1826]
kent beck scrum loading crashed - this might be the error for the log

```
2017-09-22T15:14:45.078727+00:00 app[web.1]: Processing by EventsController#show as HTML
2017-09-22T15:14:45.040799+00:00 app[web.1]: source=rack-timeout id=82a688cf-8ba4-43f2-8aa8-d15a7bd100dd wait=7ms timeout=20000ms service=6162ms state=completed
2017-09-22T15:14:45.047387+00:00 heroku[router]: at=info method=GET path="/" host=www.agileventures.org request_id=82a688cf-8ba4-43f2-8aa8-d15a7bd100dd fwd="61.6.144.14" dyno=web.1 connect=2ms service=6171ms status=200 bytes=22674 protocol=https
2017-09-22T15:14:46.878936+00:00 app[web.1]:   Rendered layouts/_sidebar.html.erb (6780.6ms)
2017-09-22T15:14:46.982086+00:00 app[web.1]:   Rendered layouts/_sponsors.html.erb (102.6ms)
2017-09-22T15:14:46.984162+00:00 app[web.1]:   Rendered layouts/_meta_tags.html.erb (1.0ms)
2017-09-22T15:14:46.985129+00:00 app[web.1]:   Rendered layouts/_head.html.erb (2.3ms)
2017-09-22T15:14:47.489703+00:00 app[web.1]:   Rendered layouts/_flash.html.erb (0.3ms)
2017-09-22T15:14:47.489837+00:00 app[web.1]:   Rendered layouts/_navbar.html.erb (504.5ms)
2017-09-22T15:14:47.798741+00:00 heroku[router]: at=info method=HEAD path="/" host=www.agileventures.org request_id=89b78fd0-a253-48eb-aa1c-574af5539aef fwd="54.247.188.179" dyno=web.1 connect=7ms service=499ms status=301 bytes=143 protocol=http
2017-09-22T15:14:47.790236+00:00 app[web.1]:   Rendered layouts/_footer.html.erb (299.9ms)
2017-09-22T15:14:47.790365+00:00 app[web.1]:   Rendered layouts/application.html.erb (807.9ms)
2017-09-22T15:14:47.790841+00:00 app[web.1]: Completed 200 OK in 8402ms (Views: 365.8ms | ActiveRecord: 7827.0ms)
2017-09-22T15:14:47.792792+00:00 app[web.1]: source=rack-timeout id=2ae1eef7-60b6-4cba-b464-d8fcdabc9990 wait=458ms timeout=20000ms service=8409ms state=completed
2017-09-22T15:14:47.801616+00:00 heroku[router]: at=info method=GET path="/projects/cs-545" host=www.agileventures.org request_id=2ae1eef7-60b6-4cba-b464-d8fcdabc9990 fwd="5.255.250.77" dyno=web.1 connect=1ms service=8873ms status=200 bytes=9659 protocol=https
2017-09-22T15:15:01.500927+00:00 app[web.1]:   Rendered event_instances/_hangout_button.html.erb (10.2ms)
2017-09-22T15:15:05.060760+00:00 app[web.1]: source=rack-timeout id=e922f2d7-dd6e-41b8-a187-1fff1d8b6d8c wait=4041ms timeout=20000ms service=20005ms state=timed_out
2017-09-22T15:15:05.218528+00:00 app[web.1]:   Rendered events/show.html.erb within layouts/application (19688.3ms)
2017-09-22T15:15:05.219157+00:00 app[web.1]: Request waited 4041ms, then ran for longer than 20000ms
2017-09-22T15:15:05.219218+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/ice_cube-0.11.1/lib/ice_cube/validated_rule.rb:139:in `min'
2017-09-22T15:15:05.219270+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/ice_cube-0.11.1/lib/ice_cube/validated_rule.rb:139:in `shift_time_by_validation'
2017-09-22T15:15:05.219309+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/ice_cube-0.11.1/lib/ice_cube/validated_rule.rb:123:in `validation_accepts_or_updates_time?'
2017-09-22T15:15:05.219346+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/ice_cube-0.11.1/lib/ice_cube/validated_rule.rb:104:in `block in finds_acceptable_time?'
2017-09-22T15:15:05.219392+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/ice_cube-0.11.1/lib/ice_cube/validated_rule.rb:103:in `each'
2017-09-22T15:15:05.219443+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/ice_cube-0.11.1/lib/ice_cube/validated_rule.rb:103:in `all?'
2017-09-22T15:15:05.236553+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_request.text.erb (0.8ms)
2017-09-22T15:15:05.245556+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (8.5ms)
2017-09-22T15:15:05.246842+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_session.text.erb (0.7ms)
2017-09-22T15:15:05.247295+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2017-09-22T15:15:05.254594+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_environment.text.erb (6.7ms)
2017-09-22T15:15:05.255146+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
2017-09-22T15:15:05.256441+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (0.3ms)
2017-09-22T15:15:05.256909+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2017-09-22T15:15:05.257921+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_data.text.erb (0.4ms)
2017-09-22T15:15:05.258361+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2017-09-22T15:15:05.258547+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (23.5ms)
2017-09-22T15:15:05.396454+00:00 app[web.1]: 
```

have a feeling we fixed something similar on events page before - maybe show page suffering from similar ...

**Comment by tansaku** [comment]
got this today:

https://dl.dropbox.com/s/a1kql9ztnij4sxn/Screenshot%202017-10-03%2016.15.50.png?dl=0

**Comment by tansaku** [comment]
don't seem to have had any similar errors since we upgraded icecube ...

**Comment by tansaku** [comment]
Sam needs to do load testing on staging with event grab removed from home page

**Comment by tansaku** [comment]
that did seem to improve things
