### ISSUE TITLE
500 error for RFM

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2006]
Robert gets a 500 error trying to start hangouts on

https://www.agileventures.org/events/3131

```
2017-12-07T12:03:58.681488+00:00 app[web.1]: Started PUT "/hangouts/399500-26988bcd-2e60-47f9-b7c2-6b16992f5f8a" for 141.89.226.145 at 2017-12-07 12:03:58 +0000
2017-12-07T12:03:58.687235+00:00 app[web.1]: Processing by EventInstancesController#update as HTML
2017-12-07T12:03:58.687348+00:00 app[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"RtnbJhMkdgy0TQsYk1gEBIPYmAoeqgTJENDsxe0VDcU+qn3npEkeglHwTIpY5FURPT9RTMvdtyws7oawk+Or9Q==", "title"=>"Rundfunk-Mitbestimmen Meeting - Wednesday, 13th Dec at 08:00pm (UTC)", "host_id"=>"3995", "event_id"=>"3131", "url_set_directly"=>"true", "notify_hangout"=>"true", "category"=>"Scrum", "project_id"=>"144", "yt_url"=>"", "hangout_url"=>"https://hangouts.google.com/hangouts/_/epwx3wdiwbesbiipyffdsqkru4e", "id"=>"399500-26988bcd-2e60-47f9-b7c2-6b16992f5f8a"}
2017-12-07T12:03:59.009372+00:00 app[web.1]: undefined method `include?' for nil:NilClass
2017-12-07T12:03:59.009656+00:00 app[web.1]: /app/app/controllers/event_instances_controller.rb:70:in `local_request?'
2017-12-07T12:03:59.009685+00:00 app[web.1]: /app/app/controllers/event_instances_controller.rb:57:in `cors_preflight_check'
2017-12-07T12:03:59.009720+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:432:in `block in make_lambda'
2017-12-07T12:03:59.009749+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:145:in `block in halting_and_conditional'
2017-12-07T12:03:59.009777+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:504:in `block in call'
2017-12-07T12:03:59.009805+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:504:in `each'
2017-12-07T12:03:59.018637+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.2/lib/exception_notifier/views/exception_notifier/_request.text.e
```

looking at the code it seems like from Robert's browser we have no HTTP_ORIGIN set ...?

**Comment by tansaku** [comment]
I would like to test for robert with quantum, but if I upgrade firefox I lose some functionality I need for generating SPOCs ...
