### ISSUE TITLE
500 error on Martin Fowler Scrum

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2187]
@sigu and I got this the last few days - all  functionality worked including ping to slack, but ended with 500 error:

```
2018-02-28T12:02:11.715753+00:00 app[web.1]: Started GET "/events/2" for 86.145.233.4 at 2018-02-28 12:02:11 +0000
2018-02-28T12:02:11.721556+00:00 app[web.1]: Processing by EventsController#show as JS
2018-02-28T12:02:11.721633+00:00 app[web.1]:   Parameters: {"id"=>"2"}
2018-02-28T12:02:11.751414+00:00 app[web.1]:   Rendered event_instances/_hangout_button.html.erb (0.9ms)
2018-02-28T12:02:11.752397+00:00 app[web.1]:   Rendered events/_hangouts_management.html.erb (2.7ms)
2018-02-28T12:02:11.761857+00:00 app[web.1]: Completed 200 OK in 40ms (Views: 3.4ms | ActiveRecord: 12.8ms)
2018-02-28T12:02:11.765548+00:00 app[web.1]: source=rack-timeout id=28ce4503-5c66-421b-98a7-5bf111aeaec3 wait=5ms timeout=20000ms service=51ms state=completed
2018-02-28T12:02:15.181358+00:00 app[web.1]: 200
2018-02-28T12:02:15.181751+00:00 app[web.1]: uncaught throw #<ArgumentError: Required arguments :channel missing>
2018-02-28T12:02:15.181938+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/slack-ruby-client-0.11.1/lib/slack/web/api/endpoints/chat.rb:140:in `throw'
2018-02-28T12:02:15.181944+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/slack-ruby-client-0.11.1/lib/slack/web/api/endpoints/chat.rb:140:in `chat_postMessage'
2018-02-28T12:02:15.181949+00:00 app[web.1]: /app/app/services/slack_service.rb:43:in `block in send_slack_message'
2018-02-28T12:02:15.181973+00:00 app[web.1]: /app/app/services/slack_service.rb:42:in `each'
2018-02-28T12:02:15.181978+00:00 app[web.1]: /app/app/services/slack_service.rb:42:in `send_slack_message'
2018-02-28T12:02:15.181998+00:00 app[web.1]: /app/app/services/slack_service.rb:71:in `post_yt_link'
```

**Comment by sigu** [comment]
Seems there is an error on rack, really have no idea what it is. Is this discussion on ongoing in the devops channel on slack?

**Comment by tansaku** [comment]
@sigu I think the problem is in the slack service, not so much related to rack

```
uncaught throw #<ArgumentError: Required arguments :channel missing>
```

looks like this is the line throwing the error:

https://github.com/AgileVentures/WebsiteOne/blob/develop/app/services/slack_service.rb#L43

looks to me like someone changed the project association of the scrum to the AV setup scripts project, which might cause the problem  - although I see the martin fowler scrum has the same association, hmmm ....

**Comment by tansaku** [comment]
I think we might want something like:

```
real_channels = channels.reject { |c| c.empty? }
```
to ensure that the system doesn't try to ping non-existent channels ....
