### ISSUE TITLE
more realistic seed data

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2829]
even more realistic seed data would be helpful for developers testing things manually

see maybe https://github.com/rroblak/seed_dump

**Comment by tansaku** [comment]
could seed file be relying on separate rake tasks?

**Comment by tansaku** [comment]
trying to do this @dkuku but I'm getting stuck on some errors:

```
→ be rake db:seed:dump
rake aborted!
NameError: uninitialized constant EventInstances::Grape
/Users/tansaku/Documents/GitHub/AgileVentures/WebsiteOne/app/api/event_instances/api.rb:2:in `<module:EventInstances>'
/Users/tansaku/Documents/GitHub/AgileVentures/WebsiteOne/app/api/event_instances/api.rb:1:in `<top (required)>'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/dependencies/interlock.rb:11:in `loading'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/railties-5.1.6/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/railties-5.1.6/lib/rails/engine.rb:475:in `each'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/railties-5.1.6/lib/rails/engine.rb:475:in `block in eager_load!'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/railties-5.1.6/lib/rails/engine.rb:473:in `each'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/railties-5.1.6/lib/rails/engine.rb:473:in `eager_load!'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/seed_dump-3.3.1/lib/seed_dump/environment.rb:5:in `dump_using_environment'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/seed_dump-3.3.1/lib/tasks/seed_dump.rake:6:in `block (3 levels) in <top (required)>'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/airbrake-7.4.0/lib/airbrake/rake.rb:17:in `execute'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/tansaku/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
/Users/tansaku/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => db:seed:dump
(See full trace by running task with --trace)
[tansaku@Samuels-MacBook-Pro:~/Documents/Github/AgileVentures/WebsiteOne (develop)]$ 
→ be rake db:seed:dump
rake aborted!
LoadError: Unable to autoload constant Api, expected /Users/tansaku/Documents/GitHub/AgileVentures/WebsiteOne/app/api/event_instances/api.rb to define it
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:512:in `load_missing_constant'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:202:in `const_missing'
/Users/tansaku/Documents/GitHub/AgileVentures/WebsiteOne/app/controllers/api/subscriptions_controller.rb:1:in `<top (required)>'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:477:in `load'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:477:in `block in load_file'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:662:in `new_constants_in'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:476:in `load_file'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:374:in `block in require_or_load'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:36:in `block in load_interlock'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/dependencies/interlock.rb:11:in `loading'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:36:in `load_interlock'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:357:in `require_or_load'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:335:in `depend_on'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:251:in `require_dependency'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/railties-5.1.6/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/railties-5.1.6/lib/rails/engine.rb:475:in `each'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/railties-5.1.6/lib/rails/engine.rb:475:in `block in eager_load!'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/railties-5.1.6/lib/rails/engine.rb:473:in `each'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/railties-5.1.6/lib/rails/engine.rb:473:in `eager_load!'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/seed_dump-3.3.1/lib/seed_dump/environment.rb:5:in `dump_using_environment'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/seed_dump-3.3.1/lib/tasks/seed_dump.rake:6:in `block (3 levels) in <top (required)>'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/airbrake-7.4.0/lib/airbrake/rake.rb:17:in `execute'
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/tansaku/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
/Users/tansaku/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => db:seed:dump
(See full trace by running task with --trace)
```

**Comment by dkuku** [comment]
this rake command is a bit scary because it overwrites `db/seeds.rb` without asking.
I wrote new rake task
[![asciicast](https://asciinema.org/a/qarDlpRskzf95u38a4d1bCeqZ.svg)](https://asciinema.org/a/qarDlpRskzf95u38a4d1bCeqZ)

**Comment by tansaku** [comment]
not working for me @dkuku 

```
→ be rake db:seed:dump:event_instances
rake aborted!
Don't know how to build task 'db:seed:dump:event_instances' (see --tasks)
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/tansaku/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
/Users/tansaku/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)
[tansaku@Samuels-MacBook-Pro:~/Documents/Github/AgileVentures/WebsiteOne (develop)]$ 
→ be rake dump:event_instances
rake aborted!
Don't know how to build task 'dump:event_instances' (see --tasks)
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/tansaku/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
/Users/tansaku/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)
[tansaku@Samuels-MacBook-Pro:~/Documents/Github/AgileVentures/WebsiteOne (develop)]$ 
→ be rake dump:event_instance
rake aborted!
Don't know how to build task 'dump:event_instance' (see --tasks)
/Users/tansaku/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/tansaku/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
/Users/tansaku/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)

```
can you share your new rake task? thanks :-)

**Comment by dkuku** [comment]
@tansaku it's in the pr #2849

**Comment by tansaku** [comment]
@dkuku I checked out that PR branch but it doesn't work for me ... it didn't seem to affect any existing files:

```
[tansaku@Samuels-MacBook-Pro:~/Documents/Github/AgileVentures/WebsiteOne (2829_more_realistic_seed_data)]$ 
→ be rake dump:event_instance
[tansaku@Samuels-MacBook-Pro:~/Documents/Github/AgileVentures/WebsiteOne (2829_more_realistic_seed_data)]$ 
→ gst
On branch 2829_more_realistic_seed_data
Your branch is up to date with 'daniel/2829_more_realistic_seed_data'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	app/api/
	lib/tasks/admin.rake

nothing added to commit but untracked files present (use "git add" to track)

```
