### ISSUE TITLE
Issue using runSpec in docker

### ISSUE THREAD

**Issue by mtc2013** [AgileVentures/WebsiteOne#3834]
On linux and windows using docker, this error comes up when using runSpec command argument to npx:

root@e0262ecdc520:/WebsiteOne# npx jasmine-browser-runner runSpecs
Jasmine server is running here: http://localhost:37771
Jasmine tests are here:         /WebsiteOne/spec/javascripts
Source files are here:          /WebsiteOne/public/assets
 The ChromeDriver could not be found on the current PATH, trying Selenium Manager
/WebsiteOne/node_modules/selenium-webdriver/bin/linux/selenium-manager: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /WebsiteOne/node_modules/selenium-webdriver/bin/linux/selenium-manager)
Unable to obtain driver using Selenium Manager: Error: Error executing command with /WebsiteOne/node_modules/selenium-webdriver/bin/linux/selenium-manager,--browser,chrome
/WebsiteOne/node_modules/selenium-webdriver/bin/linux/selenium-manager: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /WebsiteOne/node_modules/selenium-webdriver/bin/linux/selenium-manager)
Error: The ChromeDriver could not be found on the current PATH.
      Please download the latest version of the ChromeDriver
      from http://chromedriver.storage.googleapis.com/index.html
      and ensure it can be found on your PATH.
    at new ServiceBuilder (/WebsiteOne/node_modules/selenium-webdriver/chrome.js:175:13)
    at Function.getDefaultService (/WebsiteOne/node_modules/selenium-webdriver/chrome.js:264:12)
    at Function.createSession (/WebsiteOne/node_modules/selenium-webdriver/chromium.js:669:49)
    at Function.createSession (/WebsiteOne/node_modules/selenium-webdriver/chrome.js:255:13)
    at createDriver (/WebsiteOne/node_modules/selenium-webdriver/index.js:147:33)
    at Builder.build (/WebsiteOne/node_modules/selenium-webdriver/index.js:675:16)
    at buildWebdriver (/WebsiteOne/node_modules/jasmine-browser-runner/lib/webdriver.js:33:55)
    at Object.runSpecs (/WebsiteOne/node_modules/jasmine-browser-runner/index.js:89:25)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Command.runSpecs (/WebsiteOne/node_modules/jasmine-browser-runner/lib/command.js:185:5)

**Comment by mtc2013** [comment]
Looks like an easy fix to update glibc in docker file (famous last words):

root@e0262ecdc520:/WebsiteOne# ldd --version
ldd (Debian GLIBC 2.28-10+deb10u2) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
