### ISSUE TITLE
Fix ability to create new project documents on Heroku

### ISSUE THREAD

**Issue by mattlindsey** [AgileVentures/WebsiteOne#3882]
Creating a new document when running the app locally works, but on Heroku it doesn't look like the 'new' controller action is being called.

Locally the log looks like this:
```
Started GET "/projects/websiteone/documents/new" for ::1 at 2023-04-25 18:47:11 +0000
Processing by DocumentsController#new as HTML
  Parameters: {"project_id"=>"websiteone"}
```
But on heroku I don't see the call to #new and we get an error here:
https://www.agileventures.org/projects/websiteone/documents/new

**Comment by mattlindsey** [comment]
I had forgotten to run 'rake db:migrate.'  Documents get created on Heroku now, but there is an error trying to display them:
no implicit conversion of nil into String

To see error messages try to look at a document then do 'heroku logs -n 300' to see last 300 lines of the log.
Possibly something to do with disqus:

2023-04-27T18:46:52.409351+00:00 app[web.1]: I, [2023-04-27T18:46:52.409322 #2]  INFO -- : [c2d45f64-c481-4c19-b03c-18c1a788224f] Started GET "/projects/ruralnet/documents/test-document" for 71.184.125.20 at 2023-04-27 18:46:52 +0000
2023-04-27T18:46:52.410310+00:00 app[web.1]: I, [2023-04-27T18:46:52.410276 #2]  INFO -- : [c2d45f64-c481-4c19-b03c-18c1a788224f] Processing by DocumentsController#show as HTML
2023-04-27T18:46:52.410328+00:00 app[web.1]: I, [2023-04-27T18:46:52.410314 #2]  INFO -- : [c2d45f64-c481-4c19-b03c-18c1a788224f]   Parameters: {"project_id"=>"ruralnet", "id"=>"test-document"}
2023-04-27T18:46:52.432605+00:00 app[web.1]: I, [2023-04-27T18:46:52.432546 #2]  INFO -- : [c2d45f64-c481-4c19-b03c-18c1a788224f]   Rendered documents/show.html.erb within layouts/with_sidebar (Duration: 17.1ms | Allocations: 5818)
2023-04-27T18:46:52.432624+00:00 app[web.1]: I, [2023-04-27T18:46:52.432605 #2]  INFO -- : [c2d45f64-c481-4c19-b03c-18c1a788224f]   Rendered layout layouts/with_sidebar.html.erb (Duration: 17.2ms | Allocations: 5848)
2023-04-27T18:46:52.432692+00:00 app[web.1]: E, [2023-04-27T18:46:52.432674 #2] ERROR -- : [c2d45f64-c481-4c19-b03c-18c1a788224f] no implicit conversion of nil into String
2023-04-27T18:46:52.432705+00:00 app[web.1]: E, [2023-04-27T18:46:52.432690 #2] ERROR -- : [c2d45f64-c481-4c19-b03c-18c1a788224f] /app/vendor/ruby-3.2.1/lib/ruby/3.2.0/openssl/hmac.rb:55:in `initialize'
2023-04-27T18:46:52.432712+00:00 app[web.1]: E, [2023-04-27T18:46:52.432701 #2] ERROR -- : [c2d45f64-c481-4c19-b03c-18c1a788224f] /app/vendor/ruby-3.2.1/lib/ruby/3.2.0/openssl/hmac.rb:55:in `new'
2023-04-27T18:46:52.432725+00:00 app[web.1]: E, [2023-04-27T18:46:52.432710 #2] ERROR -- : [c2d45f64-c481-4c19-b03c-18c1a788224f] /app/vendor/ruby-3.2.1/lib/ruby/3.2.0/openssl/hmac.rb:55:in `hexdigest'
2023-04-27T18:46:52.432732+00:00 app[web.1]: E, [2023-04-27T18:46:52.432720 #2] ERROR -- : [c2d45f64-c481-4c19-b03c-18c1a788224f] /app/app/helpers/disqus_helper.rb:18:in `get_disqus_sso'
2023-04-27T18:46:52.432749+00:00 app[web.1]: E, [2023-04-27T18:46:52.432728 #2] ERROR -- : [c2d45f64-c481-4c19-b03c-18c1a788224f] /app/app/views/disqus/_disqus.html.erb:2:in `_app_views_disqus__disqus_html_erb___3557261068375778589_133480'
