### ISSUE TITLE
junk in the rspec log

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#749]
Would like to get this all cleaned out:

```
$ bundle exec rspec -fp

Randomized with seed 43332
..................................................................................................-- add_column(:events, :start_time, :time)
   -> 0.0253s
-- add_column(:events, :event_date, :date)
   -> 0.0008s
-- add_column(:events, :end_time, :time)
   -> 0.0019s
-- remove_column(:events, :start_datetime, :datetime)
   -> 0.0053s
-- remove_column(:events, :duration, :integer)
   -> 0.0003s
.-- add_column(:events, :start_time, :time)
   -> 0.0005s
-- add_column(:events, :event_date, :date)
   -> 0.0003s
-- add_column(:events, :end_time, :time)
   -> 0.0003s
-- remove_column(:events, :start_datetime, :datetime)
   -> 0.0004s
-- remove_column(:events, :duration, :integer)
   -> 0.0003s
-- add_column(:events, :start_datetime, :datetime)
   -> 0.0005s
-- add_index(:events, :start_datetime)
   -> 0.0202s
-- add_column(:events, :duration, :integer)
   -> 0.0008s
-- remove_column(:events, :start_time, :time)
   -> 0.0004s
-- remove_column(:events, :event_date, :date)
   -> 0.0003s
-- remove_column(:events, :end_time, :time)
   -> 0.0003s
............................................................................................../Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:24: warning: already initialized constant Newsletter::CHUNK_SIZE
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/app/models/newsletter.rb:15: warning: previous definition of CHUNK_SIZE was here
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:25: warning: already initialized constant Newsletter::SEND_AS
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/app/models/newsletter.rb:14: warning: previous definition of SEND_AS was here
./Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:24: warning: already initialized constant Newsletter::CHUNK_SIZE
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:24: warning: previous definition of CHUNK_SIZE was here
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:25: warning: already initialized constant Newsletter::SEND_AS
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:25: warning: previous definition of SEND_AS was here
..../Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:42: warning: already initialized constant Newsletter::SEND_AS
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:25: warning: previous definition of SEND_AS was here
./Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:42: warning: already initialized constant Newsletter::SEND_AS
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:42: warning: previous definition of SEND_AS was here
./Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:42: warning: already initialized constant Newsletter::SEND_AS
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:42: warning: previous definition of SEND_AS was here
./Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:46: warning: already initialized constant Newsletter::CHUNK_SIZE
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:24: warning: previous definition of CHUNK_SIZE was here
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:47: warning: already initialized constant Newsletter::SEND_AS
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:42: warning: previous definition of SEND_AS was here
........*.....................................................................................The user session path is /users/sign_in
.The user session path is /users/sign_in
.The user session path is /users/sign_in
.The user session path is /users/sign_in
.The user session path is /users/sign_in
...............................................................................Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Andres Grimes stats are okay
Tommie Terry stats are okay
Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Tommie Terry stats are okay
Andres Grimes stats are okay
.Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Domenick Feest stats are okay
Mohamed Toy stats are okay
Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Mohamed Toy stats are okay
Domenick Feest stats are okay
.Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Alene Ankunding stats are okay
Liam Kassulke stats are okay
Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Liam Kassulke stats are okay
Alene Ankunding stats are okay
.Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Charles Tillman stats are okay
Jocelyn Huel stats are okay
Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Jocelyn Huel stats are okay
Charles Tillman stats are okay
.Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Emiliano Leannon stats are okay
Chandler Corkery stats are okay
Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Chandler Corkery stats are okay
Emiliano Leannon stats are okay
.Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Jeanette Hills stats are okay
Adalberto Daniel stats are okay
Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Adalberto Daniel stats are okay
Jeanette Hills stats are okay
................................................................................................................................../Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/jobs/send_newsletter_spec.rb:7: warning: already initialized constant Newsletter::CHUNK_SIZE
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:46: warning: previous definition of CHUNK_SIZE was here
./Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/jobs/send_newsletter_spec.rb:7: warning: already initialized constant Newsletter::CHUNK_SIZE
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/jobs/send_newsletter_spec.rb:7: warning: previous definition of CHUNK_SIZE was here
./Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/jobs/send_newsletter_spec.rb:7: warning: already initialized constant Newsletter::CHUNK_SIZE
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/jobs/send_newsletter_spec.rb:7: warning: previous definition of CHUNK_SIZE was here
./Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/jobs/send_newsletter_spec.rb:7: warning: already initialized constant Newsletter::CHUNK_SIZE
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/jobs/send_newsletter_spec.rb:7: warning: previous definition of CHUNK_SIZE was here
./Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/jobs/send_newsletter_spec.rb:7: warning: already initialized constant Newsletter::CHUNK_SIZE
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/jobs/send_newsletter_spec.rb:7: warning: previous definition of CHUNK_SIZE was here
./Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/jobs/send_newsletter_spec.rb:14: warning: already initialized constant Newsletter::CHUNK_SIZE
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/jobs/send_newsletter_spec.rb:7: warning: previous definition of CHUNK_SIZE was here
...............................invalid keys :visible, should be one of :text, :visible, :between, :count, :maximum, :minimum, :exact, :match, :wait
...............................................................................................................................................................................An expectation of :includes was set on nil. Called from /Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/controllers/projects_controller_spec.rb:46:in `block (3 levels) in <top (required)>'. Use allow_message_expectations_on_nil to disable warnings.
................................................................................................................

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) events/new user is not signed in should redirect to sign in and render a flash error
     # Temporarily skipped with xit
     # ./spec/views/events/new.html.erb_spec.rb:18


Deprecation Warnings:

Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(:rspec) { |c| c.syntax = :should }` instead. Called from /Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/routing/newsletters_routing_spec.rb:22:in `block (3 levels) in <top (required)>'.

Using `stub` from rspec-mocks' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` instead. Called from /Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/views/static_page/show.html.erb_spec.rb:24:in `block (2 levels) in <top (required)>'.


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

2 deprecation warnings total

Finished in 1 minute 28.77 seconds (files took 10.27 seconds to load)
836 examples, 0 failures, 1 pending

```

**Comment by tansaku** [comment]
looking at `/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:42: warning: already initialized constant Newsletter::SEND_AS` since I can only find one instance of SEND_AS in the code base this probably arises from a repeated require of the newsletter class ...

**Comment by tansaku** [comment]
we can probably suppress the migration test output like so:

```
ActiveRecord::Migration.verbose = false
```

**Comment by freeranger** [comment]
Correct - https://github.com/AgileVentures/WebsiteOne/issues/835 fixes the migration test output

**Comment by freeranger** [comment]
@tansaku - Ok I've created https://github.com/AgileVentures/WebsiteOne/issues/855 for the should->expect conversion.
This PR is ready for review and hopefully merge...
