### ISSUE TITLE
schedule github count updates on heroku

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#789]
We need something like the following

![heroku scheduler details](https://www.dropbox.com/s/1p57v3q6m8hzx0v/Screenshot%202016-02-11%2016.26.11.png?dl=1)

**Comment by tansaku** [comment]
I have put the above in place - we will see if it works ....

**Comment by diraulo** [comment]
:+1:

**Comment by tochman** [comment]
We might want to run 
```
rake utils:geocode-all
```
as well... But I would like us to refactor that method to only hit the users that are NOT geocoded and/or have been logged in during the pas week or two. Just a thought...

**Comment by tansaku** [comment]
@tochman and you were saying there were some broken things when you tried it ...?

**Comment by diraulo** [comment]
From the scheduler's log
```shell
2016-02-24T16:32:46.263884+00:00 app[scheduler.3036]: NoMethodError: undefined method `map' for "":String
2016-02-24T16:32:46.265635+00:00 app[scheduler.3036]: (See full trace by running task with --trace)
2016-02-24T16:32:46.261723+00:00 app[scheduler.3036]: ** [Airbrake] Success: Net::HTTPOK
2016-02-24T16:32:46.264234+00:00 app[scheduler.3036]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.6/lib/active_record/relation/delegation.rb:46:in `each'
2016-02-24T16:32:46.262118+00:00 app[scheduler.3036]: rake aborted!
2016-02-24T16:32:46.264235+00:00 app[scheduler.3036]: /app/app/jobs/github_commits_job.rb:7:in `run'
2016-02-24T16:32:46.264235+00:00 app[scheduler.3036]: /app/lib/tasks/scheduler.rake:4:in `block in <top (required)>'
2016-02-24T16:32:46.265057+00:00 app[scheduler.3036]: Tasks: TOP => fetch_github_commits
2016-02-24T16:32:46.264233+00:00 app[scheduler.3036]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.6/lib/active_record/relation/delegation.rb:46:in `each'
2016-02-24T16:32:46.264230+00:00 app[scheduler.3036]: /app/app/jobs/github_commits_job.rb:30:in `update_user_commit_counts_for'
2016-02-24T16:32:46.264232+00:00 app[scheduler.3036]: /app/app/jobs/github_commits_job.rb:10:in `block in run'
2016-02-24T16:32:47.454913+00:00 heroku[scheduler.3036]: Process exited with status 1
2016-02-24T16:32:47.472128+00:00 heroku[scheduler.3036]: State changed from up to complete
```

**Comment by tansaku** [comment]
thanks @diraulo - I wonder if we could cherry pick just the commit that updates the github commit counts code and push that out ... maybe not as it was part of a merge ... :-(
