### ISSUE TITLE
ERROR: duplicate key value violates unique constraint "index_projects_on_slug" 

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/WebsiteOne#851]
After running tests locally a few times I am often encountering this error:

```
tony@Tonys-MacBook-Pro WebsiteOne (749_rspec_junk) $ bundle exec rspec -fp

Coverage report generated for RSpec to /Users/tony/OneDrive/Documents/Development/WSO/WebsiteOne/coverage. 361 / 911 LOC (39.63%) covered.
[Coveralls] Outside the CI environment, not sending data.
/Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/connection_adapters/postgresql_adapter.rb:834:in `get_last_result': PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_projects_on_slug" (ActiveRecord::RecordNotUnique)
DETAIL:  Key (slug)=(title-1) already exists.
: INSERT INTO "projects" ("created_at", "description", "pitch", "slug", "status", "title", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/connection_adapters/postgresql_adapter.rb:834:in `block in exec_cache'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/connection_adapters/postgresql_adapter.rb:831:in `exec_cache'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:138:in `exec_query'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:177:in `exec_insert'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:95:in `insert'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/relation.rb:64:in `insert'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/persistence.rb:503:in `_create_record'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/attribute_methods/dirty.rb:87:in `_create_record'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/callbacks.rb:306:in `block in _create_record'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `call'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `run_callbacks'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/callbacks.rb:306:in `_create_record'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/timestamp.rb:57:in `_create_record'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/persistence.rb:483:in `create_or_update'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/callbacks.rb:302:in `block in create_or_update'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `call'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `run_callbacks'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/callbacks.rb:302:in `create_or_update'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/persistence.rb:125:in `save!'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/validations.rb:57:in `save!'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/transactions.rb:273:in `block in save!'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/transactions.rb:208:in `transaction'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/transactions.rb:273:in `save!'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/factory_girl-4.5.0/lib/factory_girl/configuration.rb:14:in `block in initialize'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:15:in `[]'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:15:in `create'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:12:in `block in result'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/andand-1.3.3/lib/andand.rb:60:in `me'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `result'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/factory_girl-4.5.0/lib/factory_girl/factory.rb:42:in `run'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/notifications.rb:161:in `instrument'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:22:in `run'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
        from /Users/tony/OneDrive/Documents/Development/WSO/WebsiteOne/spec/controllers/projects_controller_spec.rb:281:in `block (3 levels) in <top (required)>'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:363:in `module_exec'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:363:in `subclass'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:253:in `block in define_example_group_method'
        from /Users/tony/OneDrive/Documents/Development/WSO/WebsiteOne/spec/controllers/projects_controller_spec.rb:280:in `block (2 levels) in <top (required)>'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:363:in `module_exec'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:363:in `subclass'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:253:in `block in define_example_group_method'
        from /Users/tony/OneDrive/Documents/Development/WSO/WebsiteOne/spec/controllers/projects_controller_spec.rb:233:in `block in <top (required)>'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:363:in `module_exec'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:363:in `subclass'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:253:in `block in define_example_group_method'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/dsl.rb:43:in `block in expose_example_group_alias'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/dsl.rb:82:in `block (2 levels) in expose_example_group_alias_globally'
        from /Users/tony/OneDrive/Documents/Development/WSO/WebsiteOne/spec/controllers/projects_controller_spec.rb:3:in `<top (required)>'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/zeus-0.15.4/lib/zeus/load_tracking.rb:50:in `load'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/zeus-0.15.4/lib/zeus/load_tracking.rb:50:in `load'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/zeus-0.15.4/lib/zeus/load_tracking.rb:43:in `load'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in `block in load'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in `load'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `each'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:97:in `setup'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:85:in `run'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:70:in `run'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:38:in `invoke'
        from /Users/tony/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/exe/rspec:4:in `<top (required)>'
        from /Users/tony/.rvm/gems/ruby-2.2.2/bin/rspec:23:in `load'
        from /Users/tony/.rvm/gems/ruby-2.2.2/bin/rspec:23:in `<main>'
        from /Users/tony/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
        from /Users/tony/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

The only way I have found around this is to:

```
bundle exec rake db:reset

bundle exec rake db:migrate RAILS_ENV=test

bundle exec rake db:migrate
```

**Comment by tansaku** [comment]
interesting

**Comment by mattlindsey** [comment]
Closing old issues...
