### ISSUE TITLE
documents.feature:156 fail (intermittent js?)

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#995]
This just failed for me locally twice.  Seems to be a repeat of something we've had before:

![](https://www.dropbox.com/s/onwocq9kmlvzun6/Screenshot%202016-04-18%2016.51.35.png?dl=1)

```
    And I should see an video with source "http://www.youtube.com/embed/foo?wmode=transparent" within the Mercury Editor # features/step_definitions/contained_search_steps.rb:33
      expected to find css "iframe[src*=\"http://www.youtube.com/embed/foo?wmode=transparent\"]" but there were no matches (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/basic_steps.rb:368:in `/^I should see an video with source "([^"]*)"$/'
      ./features/step_definitions/contained_search_steps.rb:38:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/contained_search_steps.rb:38:in `/^(.*) within the (.*)$/'
      features/documents.feature:166:in `And I should see an video with source "http://www.youtube.com/embed/foo?wmode=transparent" within the Mercury Editor'
    HTML screenshot: /Users/tansaku/Documents/GitHub/AgileVentures/WebsiteOne/tmp/capybara/screenshot_2016-04-18-15-48-46.912.html
    Image screenshot: /Users/tansaku/Documents/GitHub/AgileVentures/WebsiteOne/tmp/capybara/screenshot_2016-04-18-15-48-46.912.png

Failing Scenarios:
cucumber features/documents.feature:156 # Scenario: Insert media model accepts full url youtube links

```

**Comment by mattlindsey** [comment]
Closing old issues...
