### ISSUE TITLE
features/documents.feature:169 fails intermittently (JS)

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#997]
This is frustrating as it is the one that I seemed to have made pass reliably locally with the use of the 'I check by value "youtube_url"' step, when I was forcing it to fail using screenshot dumps ...

```
  Scenario: Insert media model rejects badly formatted youtube links                                      # features/documents.feature:169
    Given I am logged in                                                                                  # features/step_definitions/user_steps.rb:19
    And I am using the Mercury Editor to edit document "Guides"                                           # features/step_definitions/mercury_steps.rb:27
    And I am focused on the "document body" within the Mercury Editor                                     # features/step_definitions/contained_search_steps.rb:33
    And I click on the "Insert Media" button within the Mercury Toolbar                                   # features/step_definitions/contained_search_steps.rb:33
    And I check by value "youtube_url"                                                                    # features/step_definitions/basic_steps.rb:347
    And I fill in "YouTube URL" with "https://www.youtube.io/watch?v=foo" within the Mercury Editor Modal # features/step_definitions/contained_search_steps.rb:33
    And I check by value "youtube_url"                                                                    # features/step_definitions/basic_steps.rb:347
    And I click "Insert Media" within the Mercury Editor Modal                                            # features/step_definitions/contained_search_steps.rb:33
    Then I should see "is invalid" within the Mercury Modal                                               # features/step_definitions/contained_search_steps.rb:33
      expected to find text "is invalid" in "Insert Media (images and videos)�� Images URL can't be blank Videos YouTube URL Vimeo URL Options Alignment Float Width Height" (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/basic_steps.rb:195:in `/^I should( not)? see "([^"]*)"$/'
      ./features/step_definitions/contained_search_steps.rb:41:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/contained_search_steps.rb:41:in `/^(.*) within the (.*)$/'
      features/documents.feature:178:in `Then I should see "is invalid" within the Mercury Modal'
    And the Mercury Editor modal window should be visible                                         
```

```
cucumber -p semaphoreci features/documents.feature:169 
```

**Comment by mattlindsey** [comment]
Closing old issues...
